using System.Collections.Generic;

namespace JimGuardian;

/// <summary>
/// App-chrome localization: nav names and the most common actions, in every
/// language the backend supports. Guidance, coaching, and safety content are
/// localized server-side by the user's language setting; this table covers
/// the frame around them. Missing keys fall back to English.
/// </summary>
public static class L10n
{
    public static string T(string key)
    {
        var lang = AppState.Current.Language;
        if (Table.TryGetValue(key, out var row))
            return row.TryGetValue(lang, out var s) ? s
                 : row.TryGetValue("en", out var en) ? en : key;
        return key;
    }

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["spec.ask"] = new() { ["en"] = "Ask them", ["es"] = "Preguntarles", ["fr"] = "Leur demander", ["de"] = "Sie fragen", ["pt"] = "Perguntar-lhes", ["it"] = "Chiedi a loro", ["ja"] = "この人に聞く", ["zh"] = "去问他们", ["hi"] = "उनसे पूछें", ["ar"] = "اسألهم" },
        ["spec.fallback"] = new() { ["en"] = "Specialist", ["es"] = "Especialista", ["fr"] = "Spécialiste", ["de"] = "Fachperson", ["pt"] = "Especialista", ["it"] = "Specialista", ["ja"] = "専門家", ["zh"] = "专家", ["hi"] = "विशेषज्ञ", ["ar"] = "المختص" },
        ["spec.held"] = new() { ["en"] = "Their reply is waiting for its owner to approve it — held, not refused.", ["es"] = "Su respuesta espera la aprobación de su propietario: retenida, no rechazada.", ["fr"] = "Leur réponse attend l'approbation de son propriétaire : retenue, pas refusée.", ["de"] = "Ihre Antwort wartet auf die Freigabe ihres Eigentümers — zurückgehalten, nicht abgelehnt.", ["pt"] = "A resposta aguarda a aprovação do seu proprietário — retida, não recusada.", ["it"] = "La loro risposta attende l'approvazione del proprietario: trattenuta, non rifiutata.", ["ja"] = "返信はオーナーの承認待ちです — 拒否ではなく保留されています。", ["zh"] = "他们的回复正在等待其所有者批准 — 是被暂存，而不是被拒绝。", ["hi"] = "उनका उत्तर उसके स्वामी की मंज़ूरी की प्रतीक्षा में है — रोका गया है, अस्वीकार नहीं।", ["ar"] = "ردّهم بانتظار موافقة مالكه — محجوز، لا مرفوض." },
        ["spec.shared"] = new() { ["en"] = "Shared", ["es"] = "Se compartió", ["fr"] = "Partagé", ["de"] = "Geteilt", ["pt"] = "Partilhado", ["it"] = "Condiviso", ["ja"] = "共有した内容", ["zh"] = "已共享", ["hi"] = "साझा किया गया", ["ar"] = "ما تمت مشاركته" },
        ["spec.via"] = new() { ["en"] = "through the tandem", ["es"] = "a través del tándem", ["fr"] = "via le tandem", ["de"] = "über das Tandem", ["pt"] = "através do tandem", ["it"] = "tramite il tandem", ["ja"] = "タンデム経由", ["zh"] = "通过双联", ["hi"] = "टैंडम के माध्यम से", ["ar"] = "عبر الاقتران" },
        ["cont.title"] = new() { ["en"] = "What carries between sessions", ["es"] = "Lo que se mantiene entre sesiones", ["fr"] = "Ce qui persiste d'une session à l'autre", ["de"] = "Was zwischen den Sitzungen bleibt", ["pt"] = "O que se mantém entre sessões", ["it"] = "Ciò che resta tra una sessione e l'altra", ["ja"] = "セッションをまたいで残るもの", ["zh"] = "在不同会话之间延续的部分", ["hi"] = "जो सत्रों के बीच बना रहता है", ["ar"] = "ما يبقى بين الجلسات" },
        ["cont.observations"] = new() { ["en"] = "observations", ["es"] = "observaciones", ["fr"] = "observations", ["de"] = "Beobachtungen", ["pt"] = "observações", ["it"] = "osservazioni", ["ja"] = "件の観測", ["zh"] = "次观察", ["hi"] = "अवलोकन", ["ar"] = "ملاحظة" },
        ["cont.shaping"] = new() { ["en"] = "shaping how the coach answers", ["es"] = "influye en cómo responde el coach", ["fr"] = "influence la façon dont le coach répond", ["de"] = "beeinflusst, wie der Coach antwortet", ["pt"] = "influencia como o coach responde", ["it"] = "influenza come risponde il coach", ["ja"] = "コーチの答え方に反映されています", ["zh"] = "正在影响教练的回答方式", ["hi"] = "कोच के उत्तर देने के तरीके को आकार दे रहा है", ["ar"] = "يؤثر في طريقة رد المدرّب" },
        ["cont.not_yet"] = new() { ["en"] = "not shaping anything yet", ["es"] = "todavía no influye en nada", ["fr"] = "n'influence encore rien", ["de"] = "beeinflusst noch nichts", ["pt"] = "ainda não influencia nada", ["it"] = "non influenza ancora nulla", ["ja"] = "まだ何にも反映されていません", ["zh"] = "尚未影响任何内容", ["hi"] = "अभी कुछ भी आकार नहीं दे रहा", ["ar"] = "لا يؤثر في شيء بعد" },
        ["cont.forget"] = new() { ["en"] = "Forget it", ["es"] = "Olvidarlo", ["fr"] = "Tout oublier", ["de"] = "Verwerfen", ["pt"] = "Esquecer", ["it"] = "Dimenticalo", ["ja"] = "破棄する", ["zh"] = "清除它", ["hi"] = "इसे भूल जाएँ", ["ar"] = "احذفه" },
        ["cont.nothing"] = new() { ["en"] = "Nothing yet.", ["es"] = "Todavía nada.", ["fr"] = "Rien pour l'instant.", ["de"] = "Noch nichts.", ["pt"] = "Ainda nada.", ["it"] = "Ancora niente.", ["ja"] = "まだ何もありません。", ["zh"] = "暂时还没有。", ["hi"] = "अभी कुछ नहीं।", ["ar"] = "لا شيء بعد." },
        ["alarm.none"] = new() { ["en"] = "Nothing open.", ["es"] = "Nada abierto.", ["fr"] = "Rien en cours.", ["de"] = "Nichts offen.", ["pt"] = "Nada aberto.", ["it"] = "Niente in corso.", ["ja"] = "未対応のものはありません。", ["zh"] = "没有未处理的警报。", ["hi"] = "कुछ भी लंबित नहीं है।", ["ar"] = "لا يوجد شيء مفتوح." },
        ["alarm.lead"] = new() { ["en"] = "An alarm appears here when somebody scans the care code on your door. Scanning it does not call an ambulance — it wakes the people watching over you, and one of them has to answer.", ["es"] = "Aquí aparece una alarma cuando alguien escanea el código de cuidado de tu puerta. Escanearlo no llama a una ambulancia: despierta a las personas que te cuidan, y una de ellas tiene que responder.", ["fr"] = "Une alerte apparaît ici lorsque quelqu'un scanne le code de soins sur votre porte. Le scanner n'appelle pas d'ambulance : cela réveille les personnes qui veillent sur vous, et l'une d'elles doit répondre.", ["de"] = "Hier erscheint ein Alarm, wenn jemand den Pflegecode an Ihrer Tür scannt. Das Scannen ruft keinen Krankenwagen — es weckt die Menschen, die über Sie wachen, und eine von ihnen muss antworten.", ["pt"] = "Um alarme aparece aqui quando alguém digitaliza o código de cuidado na sua porta. Digitalizá-lo não chama uma ambulância — desperta as pessoas que velam por si, e uma delas tem de responder.", ["it"] = "Qui compare un allarme quando qualcuno scansiona il codice di assistenza sulla tua porta. Scansionarlo non chiama un'ambulanza: sveglia le persone che vegliano su di te, e una di loro deve rispondere.", ["ja"] = "誰かが玄関のケアコードを読み取ると、ここにアラームが表示されます。読み取っても救急車は呼ばれません。あなたを見守る人たちに知らせが届き、そのうちの誰かが応答しなければなりません。", ["zh"] = "当有人扫描你门上的照护码时，这里会出现一条警报。扫描不会呼叫救护车 — 它会唤醒守护你的人，其中一人必须作出回应。", ["hi"] = "जब कोई आपके दरवाज़े पर लगे केयर कोड को स्कैन करता है, तो यहाँ एक अलार्म दिखता है। स्कैन करने से एम्बुलेंस नहीं बुलाई जाती — इससे आपकी देखभाल करने वाले लोग जागते हैं, और उनमें से किसी एक को जवाब देना होता है।", ["ar"] = "يظهر هنا إنذار عندما يمسح أحدهم رمز الرعاية على بابك. المسح لا يستدعي سيارة إسعاف — بل ينبّه من يسهرون على رعايتك، وعلى أحدهم أن يستجيب." },
        ["alarm.raised"] = new() { ["en"] = "Someone raised this", ["es"] = "Alguien lo ha activado", ["fr"] = "Quelqu'un a déclenché ceci", ["de"] = "Jemand hat dies ausgelöst", ["pt"] = "Alguém accionou isto", ["it"] = "Qualcuno ha attivato questo", ["ja"] = "誰かがこれを知らせました", ["zh"] = "有人发出了这条警报", ["hi"] = "किसी ने यह उठाया है", ["ar"] = "أطلق أحدهم هذا الإنذار" },
        ["alarm.attending"] = new() { ["en"] = "{who} is attending — still open, not resolved.", ["es"] = "{who} está atendiendo — sigue abierto, no resuelto.", ["fr"] = "{who} intervient — toujours en cours, non résolu.", ["de"] = "{who} kümmert sich darum — weiterhin offen, nicht erledigt.", ["pt"] = "{who} está a atender — ainda aberto, não resolvido.", ["it"] = "{who} se ne sta occupando — ancora aperto, non risolto.", ["ja"] = "{who} が対応中です — まだ解決していません。", ["zh"] = "{who} 正在处理 — 仍未关闭，尚未解决。", ["hi"] = "{who} देख रहे हैं — अभी भी खुला है, हल नहीं हुआ।", ["ar"] = "{who} يتولى الأمر — لا يزال مفتوحًا وغير مُنتهٍ." },
        ["alarm.going"] = new() { ["en"] = "I have this — I'm going", ["es"] = "Yo me encargo — voy en camino", ["fr"] = "Je m'en occupe — j'y vais", ["de"] = "Ich übernehme das — ich gehe hin", ["pt"] = "Eu trato disto — vou a caminho", ["it"] = "Me ne occupo io — sto andando", ["ja"] = "私が対応します — 向かいます", ["zh"] = "我来处理 — 我这就过去", ["hi"] = "मैं देख लेता हूँ — मैं जा रहा हूँ", ["ar"] = "سأتولى الأمر — أنا في طريقي" },
        ["alarm.cannot_go"] = new() { ["en"] = "Nobody can go — escalate", ["es"] = "Nadie puede ir — escalar", ["fr"] = "Personne ne peut y aller — escalader", ["de"] = "Niemand kann hin — eskalieren", ["pt"] = "Ninguém pode ir — escalar", ["it"] = "Nessuno può andare — inoltra", ["ja"] = "誰も行けません — 上位に上げる", ["zh"] = "没有人能过去 — 升级处理", ["hi"] = "कोई नहीं जा सकता — आगे बढ़ाएँ", ["ar"] = "لا أحد يستطيع الذهاب — صعِّد الأمر" },
        ["alarm.clear"] = new() { ["en"] = "It's over — clear it", ["es"] = "Ya pasó — cerrarlo", ["fr"] = "C'est terminé — clôturer", ["de"] = "Es ist vorbei — schließen", ["pt"] = "Já passou — encerrar", ["it"] = "È finita — chiudi", ["ja"] = "解決しました — 解除する", ["zh"] = "已经结束 — 关闭警报", ["hi"] = "यह खत्म हो गया — इसे बंद करें", ["ar"] = "انتهى الأمر — أغلِق الإنذار" },
        ["alarm.not_emergency"] = new() { ["en"] = "This is not an emergency service. If it is one, call your local emergency number — this screen cannot.", ["es"] = "Esto no es un servicio de emergencias. Si lo es, llama al número de emergencias de tu zona — esta pantalla no puede hacerlo.", ["fr"] = "Ceci n'est pas un service d'urgence. S'il s'agit d'une urgence, appelez votre numéro d'urgence local — cet écran ne le peut pas.", ["de"] = "Dies ist kein Notdienst. Wenn es ein Notfall ist, rufen Sie Ihre örtliche Notrufnummer an — dieser Bildschirm kann das nicht.", ["pt"] = "Isto não é um serviço de emergência. Se for uma emergência, ligue para o número de emergência local — este ecrã não o pode fazer.", ["it"] = "Questo non è un servizio di emergenza. Se lo è, chiama il numero di emergenza locale — questa schermata non può farlo.", ["ja"] = "これは緊急通報サービスではありません。緊急の場合は地域の緊急通報番号に電話してください。この画面では通報できません。", ["zh"] = "这不是紧急服务。如果情况紧急，请拨打当地的急救电话 — 本屏幕无法代为拨打。", ["hi"] = "यह आपातकालीन सेवा नहीं है। यदि यह आपात स्थिति है, तो अपने स्थानीय आपातकालीन नंबर पर कॉल करें — यह स्क्रीन ऐसा नहीं कर सकती।", ["ar"] = "هذه ليست خدمة طوارئ. إذا كانت حالة طارئة، فاتصل برقم الطوارئ المحلي — فهذه الشاشة لا تستطيع ذلك." },
        ["alarm.asking"] = new() { ["en"] = "JIM is asking: are you okay?", ["es"] = "JIM pregunta: ¿estás bien?", ["fr"] = "JIM demande : est-ce que ça va ?", ["de"] = "JIM fragt: Geht es Ihnen gut?", ["pt"] = "O JIM pergunta: está bem?", ["it"] = "JIM chiede: stai bene?", ["ja"] = "JIM が確認しています：大丈夫ですか？", ["zh"] = "JIM 在询问：你还好吗？", ["hi"] = "JIM पूछ रहा है: क्या आप ठीक हैं?", ["ar"] = "يسأل JIM: هل أنت بخير؟" },
        ["alarm.concern"] = new() { ["en"] = "A concerning reading came in ({concern}). Attempt {n} of {total} — silence sends help.", ["es"] = "Llegó una lectura preocupante ({concern}). Intento {n} de {total} — el silencio envía ayuda.", ["fr"] = "Une mesure préoccupante est arrivée ({concern}). Tentative {n} sur {total} — le silence déclenche les secours.", ["de"] = "Ein besorgniserregender Messwert ist eingegangen ({concern}). Versuch {n} von {total} — Schweigen schickt Hilfe.", ["pt"] = "Chegou uma leitura preocupante ({concern}). Tentativa {n} de {total} — o silêncio envia ajuda.", ["it"] = "È arrivata una misurazione preoccupante ({concern}). Tentativo {n} di {total} — il silenzio manda aiuto.", ["ja"] = "気がかりな測定値が届きました（{concern}）。{total} 回中 {n} 回目の確認です — 応答がなければ助けを呼びます。", ["zh"] = "收到一项令人担忧的读数（{concern}）。第 {n} 次询问，共 {total} 次 — 若无回应将请求援助。", ["hi"] = "एक चिंताजनक रीडिंग आई है ({concern})। {total} में से {n} प्रयास — चुप्पी मदद भेज देगी।", ["ar"] = "وردت قراءة مقلقة ({concern}). المحاولة {n} من {total} — الصمت يستدعي المساعدة." },
        ["alarm.im_okay"] = new() { ["en"] = "I'm okay", ["es"] = "Estoy bien", ["fr"] = "Ça va", ["de"] = "Mir geht es gut", ["pt"] = "Estou bem", ["it"] = "Sto bene", ["ja"] = "大丈夫です", ["zh"] = "我没事", ["hi"] = "मैं ठीक हूँ", ["ar"] = "أنا بخير" },
        ["alarm.tripped"] = new() { ["en"] = "The crash watch tripped: {name} was contacted. Any normal reading stands it down.", ["es"] = "La vigilancia de caídas se activó: se contactó a {name}. Cualquier lectura normal la desactiva.", ["fr"] = "La veille d'accident s'est déclenchée : {name} a été contacté. Toute mesure normale la désarme.", ["de"] = "Die Sturzwache hat ausgelöst: {name} wurde benachrichtigt. Jeder normale Messwert setzt sie zurück.", ["pt"] = "A vigilância de queda disparou: {name} foi contactado. Qualquer leitura normal desativa-a.", ["it"] = "La sorveglianza incidenti è scattata: {name} è stato contattato. Qualsiasi misurazione normale la disattiva.", ["ja"] = "クラッシュウォッチが作動しました：{name} に連絡しました。通常の測定値が届けば解除されます。", ["zh"] = "跌倒守护已触发：已联系 {name}。任何正常读数都会将其解除。", ["hi"] = "क्रैश वॉच सक्रिय हो गई: {name} से संपर्क किया गया। कोई भी सामान्य रीडिंग इसे बंद कर देती है।", ["ar"] = "تم تفعيل مراقبة الحوادث: جرى الاتصال بـ {name}. وأي قراءة طبيعية تُلغيها." },
        ["alarm.armed"] = new() { ["en"] = "Armed — {name} will be contacted after {n} unanswered attempts.", ["es"] = "Activada — se contactará a {name} tras {n} intentos sin respuesta.", ["fr"] = "Armée — {name} sera contacté après {n} tentatives sans réponse.", ["de"] = "Scharf — {name} wird nach {n} unbeantworteten Versuchen benachrichtigt.", ["pt"] = "Armada — {name} será contactado após {n} tentativas sem resposta.", ["it"] = "Attiva — {name} verrà contattato dopo {n} tentativi senza risposta.", ["ja"] = "作動中 — 応答のない確認が {n} 回続くと {name} に連絡します。", ["zh"] = "已启用 — 在 {n} 次无人应答后将联系 {name}。", ["hi"] = "सक्रिय — {n} बार उत्तर न मिलने पर {name} से संपर्क किया जाएगा।", ["ar"] = "مُفعَّلة — سيجري الاتصال بـ {name} بعد {n} محاولات دون رد." },
        ["alarm.ems"] = new() { ["en"] = "May request emergency services (relayed as a request — this app cannot itself place a call)", ["es"] = "Puede solicitar servicios de emergencia (se transmite como una solicitud — esta app no puede llamar por sí misma)", ["fr"] = "Peut demander les services d'urgence (transmis comme une demande — cette application ne peut pas passer d'appel elle-même)", ["de"] = "Darf Rettungsdienste anfordern (als Anfrage weitergeleitet — diese App kann selbst nicht anrufen)", ["pt"] = "Pode pedir serviços de emergência (transmitido como um pedido — esta aplicação não pode fazer chamadas)", ["it"] = "Può richiedere i servizi di emergenza (inoltrato come richiesta — questa app non può effettuare chiamate)", ["ja"] = "緊急サービスの要請を許可する（要請として転送されます。このアプリ自体は通報できません）", ["zh"] = "可以请求紧急服务（以请求的形式转达 — 本应用本身无法拨打电话）", ["hi"] = "आपातकालीन सेवाओं का अनुरोध कर सकता है (अनुरोध के रूप में भेजा जाता है — यह ऐप स्वयं कॉल नहीं कर सकता)", ["ar"] = "قد يطلب خدمات الطوارئ (يُنقل بوصفه طلبًا — لا يمكن لهذا التطبيق إجراء مكالمة بنفسه)" },
        ["tab.self"] = new() { ["en"] = "Me", ["es"] = "Yo", ["fr"] = "Moi", ["de"] = "Ich", ["pt"] = "Eu", ["it"] = "Io", ["ja"] = "自分", ["zh"] = "我", ["hi"] = "मैं", ["ar"] = "أنا" },
        ["offline.title"] = new() { ["en"] = "What this deployment can reach", ["es"] = "Qué puede alcanzar esta instalación", ["fr"] = "Ce que ce déploiement peut atteindre", ["de"] = "Was diese Installation erreichen kann", ["pt"] = "O que esta instalação pode alcançar", ["it"] = "Cosa può raggiungere questa installazione", ["ja"] = "この環境が接続できる範囲", ["zh"] = "此部署可以连接到什么", ["hi"] = "यह परिनियोजन किस तक पहुँच सकता है", ["ar"] = "ما يمكن أن يصل إليه هذا النشر" },
        ["offline.on"] = new() { ["en"] = "Offline — nothing leaves this machine", ["es"] = "Sin conexión — nada sale de esta máquina", ["fr"] = "Hors ligne — rien ne quitte cette machine", ["de"] = "Offline — nichts verlässt diesen Rechner", ["pt"] = "Offline — nada sai desta máquina", ["it"] = "Offline — nulla esce da questa macchina", ["ja"] = "オフライン — このマシンから何も出ません", ["zh"] = "离线 — 任何内容都不会离开这台机器", ["hi"] = "ऑफ़लाइन — इस मशीन से कुछ भी बाहर नहीं जाता", ["ar"] = "دون اتصال — لا شيء يغادر هذا الجهاز" },
        ["offline.off"] = new() { ["en"] = "Online — this deployment can reach other machines", ["es"] = "En línea — esta instalación puede alcanzar otras máquinas", ["fr"] = "En ligne — ce déploiement peut atteindre d’autres machines", ["de"] = "Online — diese Installation kann andere Rechner erreichen", ["pt"] = "Online — esta instalação pode alcançar outras máquinas", ["it"] = "Online — questa installazione può raggiungere altre macchine", ["ja"] = "オンライン — この環境は他のマシンに接続できます", ["zh"] = "在线 — 此部署可以连接其他机器", ["hi"] = "ऑनलाइन — यह परिनियोजन अन्य मशीनों तक पहुँच सकता है", ["ar"] = "متصل — يمكن لهذا النشر الوصول إلى أجهزة أخرى" },
        ["self.profile_id"] = new() { ["en"] = "prf_…", ["es"] = "prf_…", ["fr"] = "prf_…", ["de"] = "prf_…", ["pt"] = "prf_…", ["it"] = "prf_…", ["ja"] = "prf_…", ["zh"] = "prf_…", ["hi"] = "prf_…", ["ar"] = "prf_…" },
        ["self.title"] = new() { ["en"] = "Your own profile", ["es"] = "Tu propio perfil", ["fr"] = "Votre propre profil", ["de"] = "Ihr eigenes Profil", ["pt"] = "O seu próprio perfil", ["it"] = "Il tuo profilo", ["ja"] = "あなた自身のプロフィール", ["zh"] = "你自己的档案", ["hi"] = "आपकी अपनी प्रोफ़ाइल", ["ar"] = "ملفك الشخصي" },
        ["self.lead"] = new() { ["en"] = "The QRME profile that speaks as you. The Guardian tells it nothing until you say which parts it may pass on, and you can see exactly what would go before any of it does.", ["es"] = "El perfil de QRME que habla como tú. El Guardián no le cuenta nada hasta que digas qué partes puede transmitir, y puedes ver exactamente qué se enviaría antes de que se envíe.", ["fr"] = "Le profil QRME qui parle en votre nom. Le Gardien ne lui dit rien tant que vous n’avez pas indiqué ce qu’il peut transmettre, et vous voyez exactement ce qui partirait avant que quoi que ce soit parte.", ["de"] = "Das QRME-Profil, das als Sie spricht. Der Guardian sagt ihm nichts, bis Sie festlegen, was er weitergeben darf, und Sie sehen genau, was ginge, bevor irgendetwas geht.", ["pt"] = "O perfil QRME que fala como você. O Guardião não lhe conta nada até dizer que partes pode transmitir, e vê exatamente o que iria antes de qualquer coisa ir.", ["it"] = "Il profilo QRME che parla come te. Il Guardian non gli dice nulla finché non indichi cosa può trasmettere, e vedi esattamente cosa partirebbe prima che parta.", ["ja"] = "あなたとして話す QRME のプロフィールです。どの部分を伝えてよいか決めるまで、ガーディアンは何も伝えません。送られる内容は送信前にそのまま確認できます。", ["zh"] = "以你的身份说话的 QRME 档案。在你指明可以转达哪些部分之前，守护者不会告诉它任何事，而且发送前你能看到确切会送出什么。", ["hi"] = "वह QRME प्रोफ़ाइल जो आपके रूप में बोलती है। जब तक आप यह न बताएँ कि कौन-से हिस्से भेजे जा सकते हैं, गार्जियन उसे कुछ नहीं बताता, और भेजे जाने से पहले आप ठीक-ठीक देख सकते हैं कि क्या जाएगा।", ["ar"] = "ملف QRME الذي يتحدث بصفتك. لا يخبره الحارس بشيء حتى تحدد ما يمكن نقله، ويمكنك أن ترى بالضبط ما سيُرسل قبل أن يُرسل أي شيء." },
        ["self.link"] = new() { ["en"] = "Link it", ["es"] = "Vincúlalo", ["fr"] = "Le relier", ["de"] = "Verknüpfen", ["pt"] = "Ligar", ["it"] = "Collegalo", ["ja"] = "リンクする", ["zh"] = "关联它", ["hi"] = "इसे जोड़ें", ["ar"] = "اربطه" },
        ["self.paste"] = new() { ["en"] = "Paste the profile's id and your owner token from QRME. It has to be a profile QRME calls your own — a made-up one will be refused.", ["es"] = "Pega el id del perfil y tu token de propietario de QRME. Tiene que ser un perfil que QRME considere tuyo; uno inventado será rechazado.", ["fr"] = "Collez l’identifiant du profil et votre jeton de propriétaire QRME. Ce doit être un profil que QRME reconnaît comme le vôtre ; un profil inventé sera refusé.", ["de"] = "Fügen Sie die Profil-ID und Ihr Eigentümer-Token aus QRME ein. Es muss ein Profil sein, das QRME als Ihr eigenes führt — ein erfundenes wird abgelehnt.", ["pt"] = "Cole o id do perfil e o seu token de proprietário do QRME. Tem de ser um perfil que o QRME considere seu — um inventado será recusado.", ["it"] = "Incolla l’id del profilo e il tuo token di proprietario da QRME. Deve essere un profilo che QRME riconosce come tuo — uno inventato verrà rifiutato.", ["ja"] = "QRME のプロフィール ID と所有者トークンを貼り付けてください。QRME があなた自身のものと認めるプロフィールに限られ、架空のものは拒否されます。", ["zh"] = "粘贴档案 id 和你在 QRME 的所有者令牌。必须是 QRME 认定属于你自己的档案 — 编造的会被拒绝。", ["hi"] = "QRME से प्रोफ़ाइल का id और अपना स्वामी टोकन चिपकाएँ। यह ऐसी प्रोफ़ाइल होनी चाहिए जिसे QRME आपकी अपनी मानता हो — बनावटी को अस्वीकार कर दिया जाएगा।", ["ar"] = "الصق معرِّف الملف ورمز المالك الخاص بك من QRME. يجب أن يكون ملفًا يعتبره QRME ملكك — وسيُرفض أي ملف مُختلق." },
        ["self.owner_token"] = new() { ["en"] = "owner token", ["es"] = "token de propietario", ["fr"] = "jeton de propriétaire", ["de"] = "Eigentümer-Token", ["pt"] = "token de proprietário", ["it"] = "token di proprietario", ["ja"] = "所有者トークン", ["zh"] = "所有者令牌", ["hi"] = "स्वामी टोकन", ["ar"] = "رمز المالك" },
        ["self.link_button"] = new() { ["en"] = "Link this profile", ["es"] = "Vincular este perfil", ["fr"] = "Relier ce profil", ["de"] = "Dieses Profil verknüpfen", ["pt"] = "Ligar este perfil", ["it"] = "Collega questo profilo", ["ja"] = "このプロフィールをリンク", ["zh"] = "关联此档案", ["hi"] = "इस प्रोफ़ाइल को जोड़ें", ["ar"] = "اربط هذا الملف" },
        ["self.may_know"] = new() { ["en"] = "What it may know", ["es"] = "Qué puede saber", ["fr"] = "Ce qu’il peut savoir", ["de"] = "Was es wissen darf", ["pt"] = "O que pode saber", ["it"] = "Cosa può sapere", ["ja"] = "伝えてよいこと", ["zh"] = "它可以知道什么", ["hi"] = "यह क्या जान सकता है", ["ar"] = "ما يمكن أن يعرفه" },
        ["self.until_tick"] = new() { ["en"] = "Nothing is passed on until you tick it.", ["es"] = "No se transmite nada hasta que lo marques.", ["fr"] = "Rien n’est transmis tant que vous ne l’avez pas coché.", ["de"] = "Nichts wird weitergegeben, bis Sie es ankreuzen.", ["pt"] = "Nada é transmitido até o marcar.", ["it"] = "Non viene trasmesso nulla finché non lo spunti.", ["ja"] = "チェックするまで何も伝えられません。", ["zh"] = "在你勾选之前，不会转达任何内容。", ["hi"] = "जब तक आप चुनें नहीं, कुछ भी नहीं भेजा जाता।", ["ar"] = "لا يُنقل شيء حتى تحدده." },
        ["self.exactly"] = new() { ["en"] = "Exactly what would be sent", ["es"] = "Exactamente lo que se enviaría", ["fr"] = "Exactement ce qui serait envoyé", ["de"] = "Genau das, was gesendet würde", ["pt"] = "Exatamente o que seria enviado", ["it"] = "Esattamente ciò che verrebbe inviato", ["ja"] = "送られる内容そのもの", ["zh"] = "确切会发送的内容", ["hi"] = "ठीक वही जो भेजा जाएगा", ["ar"] = "ما سيُرسل بالضبط" },
        ["self.nothing_ticked"] = new() { ["en"] = "Nothing, because nothing is ticked.", ["es"] = "Nada, porque no hay nada marcado.", ["fr"] = "Rien, parce que rien n’est coché.", ["de"] = "Nichts, weil nichts angekreuzt ist.", ["pt"] = "Nada, porque nada está marcado.", ["it"] = "Niente, perché non è spuntato nulla.", ["ja"] = "何もチェックされていないため、何もありません。", ["zh"] = "没有内容，因为没有勾选任何项。", ["hi"] = "कुछ नहीं, क्योंकि कुछ चुना नहीं गया है।", ["ar"] = "لا شيء، لأنه لم يتم تحديد أي شيء." },
        ["self.message_itself"] = new() { ["en"] = "This is the message itself, not a description of it. Medication is the one part made of your own words, so it shows the names as you typed them.", ["es"] = "Este es el mensaje en sí, no una descripción. La medicación es la única parte hecha con tus propias palabras, así que muestra los nombres tal como los escribiste.", ["fr"] = "Ceci est le message lui-même, pas sa description. Les médicaments sont la seule partie faite de vos propres mots : les noms s’affichent tels que vous les avez saisis.", ["de"] = "Dies ist die Nachricht selbst, keine Beschreibung. Die Medikation ist der einzige Teil aus Ihren eigenen Worten, daher erscheinen die Namen so, wie Sie sie eingegeben haben.", ["pt"] = "Esta é a mensagem em si, não uma descrição. A medicação é a única parte feita das suas próprias palavras, por isso mostra os nomes tal como os escreveu.", ["it"] = "Questo è il messaggio stesso, non una sua descrizione. I farmaci sono l’unica parte fatta di parole tue, quindi i nomi appaiono come li hai scritti.", ["ja"] = "これは説明ではなく、メッセージそのものです。薬だけはご自身の言葉でできているため、入力したとおりの名称が表示されます。", ["zh"] = "这就是消息本身，而不是对它的描述。用药是唯一由你自己的措辞构成的部分，因此名称按你输入的原样显示。", ["hi"] = "यह संदेश स्वयं है, उसका विवरण नहीं। दवा ही एकमात्र हिस्सा है जो आपके अपने शब्दों से बना है, इसलिए नाम वैसे ही दिखते हैं जैसे आपने लिखे।", ["ar"] = "هذه هي الرسالة نفسها، لا وصفٌ لها. الدواء هو الجزء الوحيد المكوَّن من كلماتك، لذا تظهر الأسماء كما كتبتها." },
        ["self.send"] = new() { ["en"] = "Send this to my profile", ["es"] = "Enviar esto a mi perfil", ["fr"] = "Envoyer ceci à mon profil", ["de"] = "Dies an mein Profil senden", ["pt"] = "Enviar isto ao meu perfil", ["it"] = "Invia questo al mio profilo", ["ja"] = "これを自分のプロフィールに送る", ["zh"] = "把这个发送到我的档案", ["hi"] = "इसे मेरी प्रोफ़ाइल को भेजें", ["ar"] = "أرسل هذا إلى ملفي" },
        ["self.stop"] = new() { ["en"] = "Stop", ["es"] = "Detener", ["fr"] = "Arrêter", ["de"] = "Beenden", ["pt"] = "Parar", ["it"] = "Ferma", ["ja"] = "やめる", ["zh"] = "停止", ["hi"] = "रोकें", ["ar"] = "إيقاف" },
        ["self.unlink_note"] = new() { ["en"] = "Unlinking removes the token and everything you ticked. What the profile was already told stays in its own source list, in QRME, where you can delete it.", ["es"] = "Desvincular elimina el token y todo lo que marcaste. Lo que ya se le dijo al perfil permanece en su propia lista de fuentes, en QRME, donde puedes borrarlo.", ["fr"] = "Le fait de délier supprime le jeton et tout ce que vous aviez coché. Ce qui a déjà été dit au profil reste dans sa liste de sources, dans QRME, où vous pouvez le supprimer.", ["de"] = "Das Trennen entfernt das Token und alles, was Sie angekreuzt hatten. Was dem Profil bereits mitgeteilt wurde, bleibt in dessen Quellenliste in QRME, wo Sie es löschen können.", ["pt"] = "Desligar remove o token e tudo o que marcou. O que já foi dito ao perfil fica na sua própria lista de fontes, no QRME, onde o pode apagar.", ["it"] = "Scollegare rimuove il token e tutto ciò che avevi spuntato. Quanto già detto al profilo resta nel suo elenco di fonti, in QRME, dove puoi eliminarlo.", ["ja"] = "リンクを解除するとトークンとチェックした内容がすべて削除されます。すでにプロフィールに伝えた内容は QRME のソース一覧に残り、そこで削除できます。", ["zh"] = "取消关联会移除令牌和你勾选的全部内容。已经告诉档案的内容仍留在 QRME 的来源列表中，你可以在那里删除。", ["hi"] = "अनलिंक करने से टोकन और आपके चुने हुए सब कुछ हट जाता है। प्रोफ़ाइल को पहले जो बताया जा चुका है वह QRME की उसकी स्रोत सूची में रहता है, जहाँ आप उसे मिटा सकते हैं।", ["ar"] = "يؤدي إلغاء الربط إلى إزالة الرمز وكل ما حددته. ويبقى ما قيل للملف سابقًا في قائمة مصادره داخل QRME، حيث يمكنك حذفه." },
        ["self.unlink"] = new() { ["en"] = "Unlink", ["es"] = "Desvincular", ["fr"] = "Délier", ["de"] = "Trennen", ["pt"] = "Desligar", ["it"] = "Scollega", ["ja"] = "リンク解除", ["zh"] = "取消关联", ["hi"] = "अनलिंक करें", ["ar"] = "إلغاء الربط" },
        ["self.linked_note"] = new() { ["en"] = "Linked. Nothing is shared yet.", ["es"] = "Vinculado. Todavía no se comparte nada.", ["fr"] = "Relié. Rien n’est encore partagé.", ["de"] = "Verknüpft. Es wird noch nichts geteilt.", ["pt"] = "Ligado. Ainda não é partilhado nada.", ["it"] = "Collegato. Non è ancora condiviso nulla.", ["ja"] = "リンクしました。まだ何も共有されていません。", ["zh"] = "已关联。尚未共享任何内容。", ["hi"] = "जुड़ गया। अभी कुछ भी साझा नहीं किया गया।", ["ar"] = "تم الربط. لم تتم مشاركة أي شيء بعد." },
        ["self.saved"] = new() { ["en"] = "Saved.", ["es"] = "Guardado.", ["fr"] = "Enregistré.", ["de"] = "Gespeichert.", ["pt"] = "Guardado.", ["it"] = "Salvato.", ["ja"] = "保存しました。", ["zh"] = "已保存。", ["hi"] = "सहेजा गया।", ["ar"] = "تم الحفظ." },
        ["self.sent"] = new() { ["en"] = "Sent.", ["es"] = "Enviado.", ["fr"] = "Envoyé.", ["de"] = "Gesendet.", ["pt"] = "Enviado.", ["it"] = "Inviato.", ["ja"] = "送信しました。", ["zh"] = "已发送。", ["hi"] = "भेज दिया गया।", ["ar"] = "تم الإرسال." },
        ["self.unlinked"] = new() { ["en"] = "Unlinked.", ["es"] = "Desvinculado.", ["fr"] = "Délié.", ["de"] = "Getrennt.", ["pt"] = "Desligado.", ["it"] = "Scollegato.", ["ja"] = "リンクを解除しました。", ["zh"] = "已取消关联。", ["hi"] = "अनलिंक कर दिया गया।", ["ar"] = "تم إلغاء الربط." },
        ["tab.overview"] = new() { ["en"] = "Overview", ["es"] = "Resumen", ["fr"] = "Aperçu", ["de"] = "Übersicht", ["pt"] = "Visão geral", ["it"] = "Panoramica", ["ja"] = "概要", ["zh"] = "概览", ["hi"] = "अवलोकन", ["ar"] = "نظرة عامة" },
        ["tab.monitor"] = new() { ["en"] = "Live Monitoring", ["es"] = "Monitoreo", ["fr"] = "Surveillance", ["de"] = "Überwachung", ["pt"] = "Monitoramento", ["it"] = "Monitoraggio", ["ja"] = "モニタリング", ["zh"] = "实时监测", ["hi"] = "निगरानी", ["ar"] = "المراقبة" },
        ["tab.checkin"] = new() { ["en"] = "Check-in", ["es"] = "Registro", ["fr"] = "Bilan", ["de"] = "Check-in", ["pt"] = "Check-in", ["it"] = "Check-in", ["ja"] = "チェックイン", ["zh"] = "签到", ["hi"] = "चेक-इन", ["ar"] = "تسجيل الحالة" },
        ["tab.coach"] = new() { ["en"] = "Coach", ["es"] = "Coach", ["fr"] = "Coach", ["de"] = "Coach", ["pt"] = "Coach", ["it"] = "Coach", ["ja"] = "コーチ", ["zh"] = "教练", ["hi"] = "कोच", ["ar"] = "مدرب" },
        ["tab.life"] = new() { ["en"] = "Life", ["es"] = "Vida", ["fr"] = "Vie", ["de"] = "Leben", ["pt"] = "Vida", ["it"] = "Vita", ["ja"] = "ライフ", ["zh"] = "生活", ["hi"] = "जीवन", ["ar"] = "الحياة" },
        ["tab.safety"] = new() { ["en"] = "Safety", ["es"] = "Seguridad", ["fr"] = "Sécurité", ["de"] = "Sicherheit", ["pt"] = "Segurança", ["it"] = "Sicurezza", ["ja"] = "安全", ["zh"] = "安全", ["hi"] = "सुरक्षा", ["ar"] = "السلامة" },
        ["tab.connect"] = new() { ["en"] = "Connect", ["es"] = "Conectar", ["fr"] = "Connecter", ["de"] = "Verbinden", ["pt"] = "Conectar", ["it"] = "Connetti", ["ja"] = "接続", ["zh"] = "连接", ["hi"] = "कनेक्ट", ["ar"] = "اتصال" },
        ["tab.custody"] = new() { ["en"] = "Vault Custody", ["es"] = "Custodia", ["fr"] = "Conservation", ["de"] = "Verwahrung", ["pt"] = "Custódia", ["it"] = "Custodia", ["ja"] = "保管", ["zh"] = "保管记录", ["hi"] = "अभिरक्षा", ["ar"] = "الحفظ" },
        ["tab.family"] = new() { ["en"] = "Family", ["es"] = "Familia", ["fr"] = "Famille", ["de"] = "Familie", ["pt"] = "Família", ["it"] = "Famiglia", ["ja"] = "家族", ["zh"] = "家庭", ["hi"] = "परिवार", ["ar"] = "العائلة" },
        ["action.send"] = new() { ["en"] = "Send", ["es"] = "Enviar", ["fr"] = "Envoyer", ["de"] = "Senden", ["pt"] = "Enviar", ["it"] = "Invia", ["ja"] = "送信", ["zh"] = "发送", ["hi"] = "भेजें", ["ar"] = "إرسال" },
        ["action.save"] = new() { ["en"] = "Save", ["es"] = "Guardar", ["fr"] = "Enregistrer", ["de"] = "Speichern", ["pt"] = "Salvar", ["it"] = "Salva", ["ja"] = "保存", ["zh"] = "保存", ["hi"] = "सहेजें", ["ar"] = "حفظ" },
        ["action.translate"] = new() { ["en"] = "Translate", ["es"] = "Traducir", ["fr"] = "Traduire", ["de"] = "Übersetzen", ["pt"] = "Traduzir", ["it"] = "Traduci", ["ja"] = "翻訳", ["zh"] = "翻译", ["hi"] = "अनुवाद", ["ar"] = "ترجمة" },
        ["action.refresh"] = new() { ["en"] = "Refresh", ["es"] = "Actualizar", ["fr"] = "Actualiser", ["de"] = "Aktualisieren", ["pt"] = "Atualizar", ["it"] = "Aggiorna", ["ja"] = "更新", ["zh"] = "刷新", ["hi"] = "रीफ़्रेश", ["ar"] = "تحديث" },
    };
}
