package app.jim.guardian

import android.content.res.Resources

/**
 * App-chrome localization: tab names and the most common actions, in every
 * language the backend supports. Guidance, coaching, and safety content are
 * localized server-side by the user's language setting; this table covers
 * the frame around them. Missing keys fall back to English.
 */
object L10n {
    fun t(key: String, lang: String): String =
        table[key]?.let { it[lang] ?: it["en"] } ?: key

    val supported = listOf("en", "es", "fr", "de", "pt", "it", "ja", "zh",
                           "hi", "ar")

    /**
     * The language of somebody who has no account to take one from.
     *
     * `AppState.language` comes from the stored setting and is "en" until an
     * account exists. Every sentence the backend composes on a public route is
     * chosen from `Accept-Language`, and this shell was sending no such header
     * — the phone has been carrying the answer in the system configuration all
     * along.
     *
     * Region dropped; anything this app does not carry falls back to English
     * rather than guessing.
     */
    fun deviceLanguage(): String {
        val locales = Resources.getSystem().configuration.locales
        for (i in 0 until locales.size()) {
            val base = locales[i].language.lowercase()
            if (supported.contains(base)) return base
        }
        return "en"
    }

    private val table: Map<String, Map<String, String>> = mapOf(
        "spec.ask" to mapOf("en" to "Ask them", "es" to "Preguntarles", "fr" to "Leur demander", "de" to "Sie fragen", "pt" to "Perguntar-lhes", "it" to "Chiedi a loro", "ja" to "この人に聞く", "zh" to "去问他们", "hi" to "उनसे पूछें", "ar" to "اسألهم"),
        "spec.fallback" to mapOf("en" to "Specialist", "es" to "Especialista", "fr" to "Spécialiste", "de" to "Fachperson", "pt" to "Especialista", "it" to "Specialista", "ja" to "専門家", "zh" to "专家", "hi" to "विशेषज्ञ", "ar" to "المختص"),
        "spec.held" to mapOf("en" to "Their reply is waiting for its owner to approve it — held, not refused.", "es" to "Su respuesta espera la aprobación de su propietario: retenida, no rechazada.", "fr" to "Leur réponse attend l'approbation de son propriétaire : retenue, pas refusée.", "de" to "Ihre Antwort wartet auf die Freigabe ihres Eigentümers — zurückgehalten, nicht abgelehnt.", "pt" to "A resposta aguarda a aprovação do seu proprietário — retida, não recusada.", "it" to "La loro risposta attende l'approvazione del proprietario: trattenuta, non rifiutata.", "ja" to "返信はオーナーの承認待ちです — 拒否ではなく保留されています。", "zh" to "他们的回复正在等待其所有者批准 — 是被暂存，而不是被拒绝。", "hi" to "उनका उत्तर उसके स्वामी की मंज़ूरी की प्रतीक्षा में है — रोका गया है, अस्वीकार नहीं।", "ar" to "ردّهم بانتظار موافقة مالكه — محجوز، لا مرفوض."),
        "spec.shared" to mapOf("en" to "Shared", "es" to "Se compartió", "fr" to "Partagé", "de" to "Geteilt", "pt" to "Partilhado", "it" to "Condiviso", "ja" to "共有した内容", "zh" to "已共享", "hi" to "साझा किया गया", "ar" to "ما تمت مشاركته"),
        "spec.via" to mapOf("en" to "through the tandem", "es" to "a través del tándem", "fr" to "via le tandem", "de" to "über das Tandem", "pt" to "através do tandem", "it" to "tramite il tandem", "ja" to "タンデム経由", "zh" to "通过双联", "hi" to "टैंडम के माध्यम से", "ar" to "عبر الاقتران"),
        "cont.title" to mapOf("en" to "What carries between sessions", "es" to "Lo que se mantiene entre sesiones", "fr" to "Ce qui persiste d'une session à l'autre", "de" to "Was zwischen den Sitzungen bleibt", "pt" to "O que se mantém entre sessões", "it" to "Ciò che resta tra una sessione e l'altra", "ja" to "セッションをまたいで残るもの", "zh" to "在不同会话之间延续的部分", "hi" to "जो सत्रों के बीच बना रहता है", "ar" to "ما يبقى بين الجلسات"),
        "cont.observations" to mapOf("en" to "observations", "es" to "observaciones", "fr" to "observations", "de" to "Beobachtungen", "pt" to "observações", "it" to "osservazioni", "ja" to "件の観測", "zh" to "次观察", "hi" to "अवलोकन", "ar" to "ملاحظة"),
        "cont.shaping" to mapOf("en" to "shaping how the coach answers", "es" to "influye en cómo responde el coach", "fr" to "influence la façon dont le coach répond", "de" to "beeinflusst, wie der Coach antwortet", "pt" to "influencia como o coach responde", "it" to "influenza come risponde il coach", "ja" to "コーチの答え方に反映されています", "zh" to "正在影响教练的回答方式", "hi" to "कोच के उत्तर देने के तरीके को आकार दे रहा है", "ar" to "يؤثر في طريقة رد المدرّب"),
        "cont.not_yet" to mapOf("en" to "not shaping anything yet", "es" to "todavía no influye en nada", "fr" to "n'influence encore rien", "de" to "beeinflusst noch nichts", "pt" to "ainda não influencia nada", "it" to "non influenza ancora nulla", "ja" to "まだ何にも反映されていません", "zh" to "尚未影响任何内容", "hi" to "अभी कुछ भी आकार नहीं दे रहा", "ar" to "لا يؤثر في شيء بعد"),
        "cont.forget" to mapOf("en" to "Forget it", "es" to "Olvidarlo", "fr" to "Tout oublier", "de" to "Verwerfen", "pt" to "Esquecer", "it" to "Dimenticalo", "ja" to "破棄する", "zh" to "清除它", "hi" to "इसे भूल जाएँ", "ar" to "احذفه"),
        "cont.nothing" to mapOf("en" to "Nothing yet.", "es" to "Todavía nada.", "fr" to "Rien pour l'instant.", "de" to "Noch nichts.", "pt" to "Ainda nada.", "it" to "Ancora niente.", "ja" to "まだ何もありません。", "zh" to "暂时还没有。", "hi" to "अभी कुछ नहीं।", "ar" to "لا شيء بعد."),
        "alarm.none" to mapOf("en" to "Nothing open.", "es" to "Nada abierto.", "fr" to "Rien en cours.", "de" to "Nichts offen.", "pt" to "Nada aberto.", "it" to "Niente in corso.", "ja" to "未対応のものはありません。", "zh" to "没有未处理的警报。", "hi" to "कुछ भी लंबित नहीं है।", "ar" to "لا يوجد شيء مفتوح."),
        "alarm.lead" to mapOf("en" to "An alarm appears here when somebody scans the care code on your door. Scanning it does not call an ambulance — it wakes the people watching over you, and one of them has to answer.", "es" to "Aquí aparece una alarma cuando alguien escanea el código de cuidado de tu puerta. Escanearlo no llama a una ambulancia: despierta a las personas que te cuidan, y una de ellas tiene que responder.", "fr" to "Une alerte apparaît ici lorsque quelqu'un scanne le code de soins sur votre porte. Le scanner n'appelle pas d'ambulance : cela réveille les personnes qui veillent sur vous, et l'une d'elles doit répondre.", "de" to "Hier erscheint ein Alarm, wenn jemand den Pflegecode an Ihrer Tür scannt. Das Scannen ruft keinen Krankenwagen — es weckt die Menschen, die über Sie wachen, und eine von ihnen muss antworten.", "pt" to "Um alarme aparece aqui quando alguém digitaliza o código de cuidado na sua porta. Digitalizá-lo não chama uma ambulância — desperta as pessoas que velam por si, e uma delas tem de responder.", "it" to "Qui compare un allarme quando qualcuno scansiona il codice di assistenza sulla tua porta. Scansionarlo non chiama un'ambulanza: sveglia le persone che vegliano su di te, e una di loro deve rispondere.", "ja" to "誰かが玄関のケアコードを読み取ると、ここにアラームが表示されます。読み取っても救急車は呼ばれません。あなたを見守る人たちに知らせが届き、そのうちの誰かが応答しなければなりません。", "zh" to "当有人扫描你门上的照护码时，这里会出现一条警报。扫描不会呼叫救护车 — 它会唤醒守护你的人，其中一人必须作出回应。", "hi" to "जब कोई आपके दरवाज़े पर लगे केयर कोड को स्कैन करता है, तो यहाँ एक अलार्म दिखता है। स्कैन करने से एम्बुलेंस नहीं बुलाई जाती — इससे आपकी देखभाल करने वाले लोग जागते हैं, और उनमें से किसी एक को जवाब देना होता है।", "ar" to "يظهر هنا إنذار عندما يمسح أحدهم رمز الرعاية على بابك. المسح لا يستدعي سيارة إسعاف — بل ينبّه من يسهرون على رعايتك، وعلى أحدهم أن يستجيب."),
        "alarm.raised" to mapOf("en" to "Someone raised this", "es" to "Alguien lo ha activado", "fr" to "Quelqu'un a déclenché ceci", "de" to "Jemand hat dies ausgelöst", "pt" to "Alguém accionou isto", "it" to "Qualcuno ha attivato questo", "ja" to "誰かがこれを知らせました", "zh" to "有人发出了这条警报", "hi" to "किसी ने यह उठाया है", "ar" to "أطلق أحدهم هذا الإنذار"),
        "alarm.attending" to mapOf("en" to "{who} is attending — still open, not resolved.", "es" to "{who} está atendiendo — sigue abierto, no resuelto.", "fr" to "{who} intervient — toujours en cours, non résolu.", "de" to "{who} kümmert sich darum — weiterhin offen, nicht erledigt.", "pt" to "{who} está a atender — ainda aberto, não resolvido.", "it" to "{who} se ne sta occupando — ancora aperto, non risolto.", "ja" to "{who} が対応中です — まだ解決していません。", "zh" to "{who} 正在处理 — 仍未关闭，尚未解决。", "hi" to "{who} देख रहे हैं — अभी भी खुला है, हल नहीं हुआ।", "ar" to "{who} يتولى الأمر — لا يزال مفتوحًا وغير مُنتهٍ."),
        "alarm.going" to mapOf("en" to "I have this — I'm going", "es" to "Yo me encargo — voy en camino", "fr" to "Je m'en occupe — j'y vais", "de" to "Ich übernehme das — ich gehe hin", "pt" to "Eu trato disto — vou a caminho", "it" to "Me ne occupo io — sto andando", "ja" to "私が対応します — 向かいます", "zh" to "我来处理 — 我这就过去", "hi" to "मैं देख लेता हूँ — मैं जा रहा हूँ", "ar" to "سأتولى الأمر — أنا في طريقي"),
        "alarm.cannot_go" to mapOf("en" to "Nobody can go — escalate", "es" to "Nadie puede ir — escalar", "fr" to "Personne ne peut y aller — escalader", "de" to "Niemand kann hin — eskalieren", "pt" to "Ninguém pode ir — escalar", "it" to "Nessuno può andare — inoltra", "ja" to "誰も行けません — 上位に上げる", "zh" to "没有人能过去 — 升级处理", "hi" to "कोई नहीं जा सकता — आगे बढ़ाएँ", "ar" to "لا أحد يستطيع الذهاب — صعِّد الأمر"),
        "alarm.clear" to mapOf("en" to "It's over — clear it", "es" to "Ya pasó — cerrarlo", "fr" to "C'est terminé — clôturer", "de" to "Es ist vorbei — schließen", "pt" to "Já passou — encerrar", "it" to "È finita — chiudi", "ja" to "解決しました — 解除する", "zh" to "已经结束 — 关闭警报", "hi" to "यह खत्म हो गया — इसे बंद करें", "ar" to "انتهى الأمر — أغلِق الإنذار"),
        "alarm.not_emergency" to mapOf("en" to "This is not an emergency service. If it is one, call your local emergency number — this screen cannot.", "es" to "Esto no es un servicio de emergencias. Si lo es, llama al número de emergencias de tu zona — esta pantalla no puede hacerlo.", "fr" to "Ceci n'est pas un service d'urgence. S'il s'agit d'une urgence, appelez votre numéro d'urgence local — cet écran ne le peut pas.", "de" to "Dies ist kein Notdienst. Wenn es ein Notfall ist, rufen Sie Ihre örtliche Notrufnummer an — dieser Bildschirm kann das nicht.", "pt" to "Isto não é um serviço de emergência. Se for uma emergência, ligue para o número de emergência local — este ecrã não o pode fazer.", "it" to "Questo non è un servizio di emergenza. Se lo è, chiama il numero di emergenza locale — questa schermata non può farlo.", "ja" to "これは緊急通報サービスではありません。緊急の場合は地域の緊急通報番号に電話してください。この画面では通報できません。", "zh" to "这不是紧急服务。如果情况紧急，请拨打当地的急救电话 — 本屏幕无法代为拨打。", "hi" to "यह आपातकालीन सेवा नहीं है। यदि यह आपात स्थिति है, तो अपने स्थानीय आपातकालीन नंबर पर कॉल करें — यह स्क्रीन ऐसा नहीं कर सकती।", "ar" to "هذه ليست خدمة طوارئ. إذا كانت حالة طارئة، فاتصل برقم الطوارئ المحلي — فهذه الشاشة لا تستطيع ذلك."),
        "alarm.asking" to mapOf("en" to "JIM is asking: are you okay?", "es" to "JIM pregunta: ¿estás bien?", "fr" to "JIM demande : est-ce que ça va ?", "de" to "JIM fragt: Geht es Ihnen gut?", "pt" to "O JIM pergunta: está bem?", "it" to "JIM chiede: stai bene?", "ja" to "JIM が確認しています：大丈夫ですか？", "zh" to "JIM 在询问：你还好吗？", "hi" to "JIM पूछ रहा है: क्या आप ठीक हैं?", "ar" to "يسأل JIM: هل أنت بخير؟"),
        "alarm.concern" to mapOf("en" to "A concerning reading came in ({concern}). Attempt {n} of {total} — silence sends help.", "es" to "Llegó una lectura preocupante ({concern}). Intento {n} de {total} — el silencio envía ayuda.", "fr" to "Une mesure préoccupante est arrivée ({concern}). Tentative {n} sur {total} — le silence déclenche les secours.", "de" to "Ein besorgniserregender Messwert ist eingegangen ({concern}). Versuch {n} von {total} — Schweigen schickt Hilfe.", "pt" to "Chegou uma leitura preocupante ({concern}). Tentativa {n} de {total} — o silêncio envia ajuda.", "it" to "È arrivata una misurazione preoccupante ({concern}). Tentativo {n} di {total} — il silenzio manda aiuto.", "ja" to "気がかりな測定値が届きました（{concern}）。{total} 回中 {n} 回目の確認です — 応答がなければ助けを呼びます。", "zh" to "收到一项令人担忧的读数（{concern}）。第 {n} 次询问，共 {total} 次 — 若无回应将请求援助。", "hi" to "एक चिंताजनक रीडिंग आई है ({concern})। {total} में से {n} प्रयास — चुप्पी मदद भेज देगी।", "ar" to "وردت قراءة مقلقة ({concern}). المحاولة {n} من {total} — الصمت يستدعي المساعدة."),
        "alarm.im_okay" to mapOf("en" to "I'm okay", "es" to "Estoy bien", "fr" to "Ça va", "de" to "Mir geht es gut", "pt" to "Estou bem", "it" to "Sto bene", "ja" to "大丈夫です", "zh" to "我没事", "hi" to "मैं ठीक हूँ", "ar" to "أنا بخير"),
        "sos" to mapOf("en" to "SOS", "es" to "SOS", "fr" to "SOS", "de" to "SOS", "pt" to "SOS", "it" to "SOS", "ja" to "SOS", "zh" to "SOS", "hi" to "SOS", "ar" to "استغاثة"),
        "sos.tap" to mapOf("en" to "Tap for emergency", "es" to "Toca para una emergencia", "fr" to "Touchez en cas d'urgence", "de" to "Für den Notfall tippen", "pt" to "Toque em caso de emergência", "it" to "Tocca in caso di emergenza", "ja" to "緊急時はタップ", "zh" to "紧急情况请点按", "hi" to "आपात स्थिति में टैप करें", "ar" to "انقر عند الطوارئ"),
        "sos.whatdo" to mapOf("en" to "What do I do?", "es" to "¿Qué hago?", "fr" to "Que dois-je faire ?", "de" to "Was soll ich tun?", "pt" to "O que faço?", "it" to "Cosa faccio?", "ja" to "どうすればいいですか？", "zh" to "我该怎么做？", "hi" to "मैं क्या करूँ?", "ar" to "ماذا أفعل؟"),
        "sos.firstaid" to mapOf("en" to "first-aid assist", "es" to "asistencia de primeros auxilios", "fr" to "assistance de premiers secours", "de" to "Erste-Hilfe-Assistenz", "pt" to "assistência de primeiros socorros", "it" to "assistenza di primo soccorso", "ja" to "応急手当の補助", "zh" to "急救辅助", "hi" to "प्राथमिक चिकित्सा सहायता", "ar" to "مساعدة الإسعاف الأولي"),
        "cw" to mapOf("en" to "Crash watch", "es" to "Vigilancia de caídas", "fr" to "Veille d'accident", "de" to "Sturzwache", "pt" to "Vigilância de queda", "it" to "Sorveglianza incidenti", "ja" to "クラッシュウォッチ", "zh" to "跌倒守护", "hi" to "क्रैश वॉच", "ar" to "مراقبة الحوادث"),
        "cw.arm" to mapOf("en" to "Arm the crash watch", "es" to "Activar la vigilancia de caídas", "fr" to "Armer la veille d'accident", "de" to "Sturzwache scharfschalten", "pt" to "Armar a vigilância de queda", "it" to "Attiva la sorveglianza incidenti", "ja" to "クラッシュウォッチを作動させる", "zh" to "启用跌倒守护", "hi" to "क्रैश वॉच सक्रिय करें", "ar" to "فعّل مراقبة الحوادث"),
        "cw.disarm" to mapOf("en" to "Disarm", "es" to "Desactivar", "fr" to "Désarmer", "de" to "Entschärfen", "pt" to "Desarmar", "it" to "Disattiva", "ja" to "解除する", "zh" to "停用", "hi" to "निष्क्रिय करें", "ar" to "ألغِ التفعيل"),
        "cw.sub" to mapOf("en" to "Off by default, programmed by you: a critical reading (a fall the watch felt, a collapsing pulse) opens “are you okay?” — unanswered attempts contact your trusted person, and emergency services only if you tick the box. Gentle drift check-ins can never trigger this.", "es" to "Desactivada por defecto y configurada por ti: una lectura crítica (una caída que el reloj notó, un pulso que se desploma) abre «¿estás bien?»; si no respondes, se contacta a tu persona de confianza, y a los servicios de emergencia solo si marcas la casilla. Las comprobaciones suaves por desviación nunca pueden dispararla.", "fr" to "Désactivée par défaut et programmée par vous : une mesure critique (une chute ressentie par la montre, un pouls qui s'effondre) ouvre « ça va ? » — sans réponse, votre personne de confiance est contactée, et les secours seulement si vous cochez la case. Les vérifications douces de dérive ne peuvent jamais la déclencher.", "de" to "Standardmäßig aus und von dir eingestellt: Ein kritischer Messwert (ein Sturz, den die Uhr gespürt hat, ein einbrechender Puls) öffnet „Alles in Ordnung?“ — bleiben die Versuche unbeantwortet, wird deine Vertrauensperson benachrichtigt, und der Rettungsdienst nur, wenn du das Kästchen setzt. Sanfte Abweichungs-Check-ins können das nie auslösen.", "pt" to "Desligada por omissão e programada por si: uma leitura crítica (uma queda que o relógio sentiu, um pulso a colapsar) abre «está bem?» — se não responder, contacta-se a sua pessoa de confiança, e os serviços de emergência só se assinalar a caixa. As verificações suaves de desvio nunca a podem disparar.", "it" to "Disattivata di default e impostata da te: una misurazione critica (una caduta che l'orologio ha sentito, un polso che crolla) apre «tutto bene?» — se non rispondi viene contattata la tua persona di fiducia, e i soccorsi solo se spunti la casella. I check-in leggeri sulla deriva non possono mai farla scattare.", "ja" to "既定では切ってあり、設定するのはあなたです。重大な測定値（時計が感じた転倒、急落する脈）が「大丈夫ですか？」を開き、応答がなければ信頼する人に連絡します。緊急サービスへの連絡は、あなたがチェックを入れた場合だけです。穏やかなドリフトの確認がこれを引き起こすことはありません。", "zh" to "默认关闭，由你来设定：一次危急读数（手表感知到的跌倒、骤降的脉搏）会弹出「你还好吗？」— 若无人应答，会联系你的信任联系人；只有你勾选了，才会联系紧急服务。温和的偏移问候永远不会触发它。", "hi" to "डिफ़ॉल्ट रूप से बंद, और इसे आप ही तय करते हैं: कोई गंभीर रीडिंग (घड़ी को महसूस हुआ गिरना, गिरती हुई नब्ज़) «क्या आप ठीक हैं?» खोलती है — उत्तर न मिलने पर आपके भरोसेमंद व्यक्ति से संपर्क होता है, और आपातकालीन सेवाओं से केवल तभी जब आपने वह विकल्प चुना हो। हल्के ड्रिफ़्ट चेक-इन इसे कभी सक्रिय नहीं कर सकते।", "ar" to "مُعطَّلة افتراضيًا وأنت من يضبطها: قراءة حرجة (سقطة شعرت بها الساعة، نبض ينهار) تفتح «هل أنت بخير؟» — وإن لم تُجب جرى الاتصال بشخصك الموثوق، وبخدمات الطوارئ فقط إن أشّرت على ذلك. ولا يمكن لاطمئنانات الانحراف اللطيفة أن تُطلقها أبدًا."),
        "cw.sensitivity" to mapOf("en" to "Sensitivity", "es" to "Sensibilidad", "fr" to "Sensibilité", "de" to "Empfindlichkeit", "pt" to "Sensibilidade", "it" to "Sensibilità", "ja" to "感度", "zh" to "灵敏度", "hi" to "संवेदनशीलता", "ar" to "الحساسية"),
        "cw.sensitivity.sub" to mapOf("en" to "Cautious escalates a rung earlier; assertive a rung later. Crisis language and critical events have floors no dial can lower.", "es" to "Cauteloso sube un peldaño antes; asertivo, uno después. El lenguaje de crisis y los eventos críticos tienen mínimos que ningún control puede bajar.", "fr" to "Prudent monte d'un cran plus tôt ; affirmé, d'un cran plus tard. Le langage de crise et les événements critiques ont des planchers qu'aucun réglage n'abaisse.", "de" to "Vorsichtig eskaliert eine Stufe früher, bestimmt eine Stufe später. Krisensprache und kritische Ereignisse haben Untergrenzen, die kein Regler senkt.", "pt" to "Cauteloso sobe um degrau mais cedo; assertivo, um mais tarde. A linguagem de crise e os eventos críticos têm mínimos que nenhum controlo baixa.", "it" to "Cauto sale di un gradino prima; assertivo di uno dopo. Il linguaggio di crisi e gli eventi critici hanno soglie minime che nessuna manopola abbassa.", "ja" to "「慎重」は一段早く、「積極」は一段遅く上げます。危機を示す言葉と重大な事象には、どのつまみでも下げられない下限があります。", "zh" to "「谨慎」提前一级升级，「果断」推后一级。危机性言语和危急事件都有任何旋钮都无法调低的下限。", "hi" to "«सतर्क» एक पायदान पहले बढ़ाता है; «दृढ़» एक पायदान बाद में। संकट की भाषा और गंभीर घटनाओं की ऐसी न्यूनतम सीमाएँ हैं जिन्हें कोई डायल नीचे नहीं कर सकता।", "ar" to "«الحذر» يصعّد درجةً أبكر، و«الحازم» درجةً أمتأخر. ولغة الأزمة والأحداث الحرجة لها حدود دنيا لا يخفضها أي مؤشر."),
        "cw.trusted" to mapOf("en" to "Trusted person", "es" to "Persona de confianza", "fr" to "Personne de confiance", "de" to "Vertrauensperson", "pt" to "Pessoa de confiança", "it" to "Persona di fiducia", "ja" to "信頼する人", "zh" to "信任的人", "hi" to "भरोसेमंद व्यक्ति", "ar" to "الشخص الموثوق"),
        "cw.reach" to mapOf("en" to "How to reach them (email or phone)", "es" to "Cómo contactarla (correo o teléfono)", "fr" to "Comment la joindre (e-mail ou téléphone)", "de" to "Wie sie erreichbar ist (E-Mail oder Telefon)", "pt" to "Como contactá-la (email ou telefone)", "it" to "Come raggiungerla (email o telefono)", "ja" to "連絡方法（メールまたは電話）", "zh" to "如何联系他们（邮箱或电话）", "hi" to "उन तक कैसे पहुँचें (ईमेल या फ़ोन)", "ar" to "كيفية الوصول إليه (بريد أو هاتف)"),
        "res.waiver" to mapOf("en" to "Autonomous-resuscitation waiver", "es" to "Consentimiento de reanimación autónoma", "fr" to "Renonciation pour réanimation autonome", "de" to "Verzichtserklärung für autonome Wiederbelebung", "pt" to "Consentimento de reanimação autónoma", "it" to "Liberatoria per rianimazione autonoma", "ja" to "自律的蘇生に関する同意書", "zh" to "自主复苏授权书", "hi" to "स्वायत्त पुनर्जीवन अनुमति-पत्र", "ar" to "تنازل الإنعاش الذاتي"),
        "res.sign.ph" to mapOf("en" to "Type your legal name to sign", "es" to "Escribe tu nombre legal para firmar", "fr" to "Saisissez votre nom légal pour signer", "de" to "Zum Unterschreiben deinen amtlichen Namen eintippen", "pt" to "Escreva o seu nome legal para assinar", "it" to "Digita il tuo nome legale per firmare", "ja" to "署名するには、法律上の氏名を入力してください", "zh" to "输入你的法定姓名以签署", "hi" to "हस्ताक्षर के लिए अपना क़ानूनी नाम लिखें", "ar" to "اكتب اسمك القانوني للتوقيع"),
        "res.sign" to mapOf("en" to "Sign & submit waiver", "es" to "Firmar y enviar el consentimiento", "fr" to "Signer et envoyer la renonciation", "de" to "Verzichtserklärung unterschreiben und senden", "pt" to "Assinar e enviar o consentimento", "it" to "Firma e invia la liberatoria", "ja" to "署名して同意書を提出", "zh" to "签署并提交授权书", "hi" to "हस्ताक्षर करें और अनुमति-पत्र भेजें", "ar" to "وقّع وأرسل التنازل"),
        "res.signed" to mapOf("en" to "SIGNED", "es" to "FIRMADO", "fr" to "SIGNÉ", "de" to "UNTERSCHRIEBEN", "pt" to "ASSINADO", "it" to "FIRMATA", "ja" to "署名済み", "zh" to "已签署", "hi" to "हस्ताक्षरित", "ar" to "موقَّع"),
        "res.revoke" to mapOf("en" to "Revoke — restore confirm-gated operation", "es" to "Revocar: volver al funcionamiento con confirmación", "fr" to "Révoquer — rétablir le fonctionnement sous confirmation", "de" to "Widerrufen — Betrieb wieder nur mit Bestätigung", "pt" to "Revogar — repor o funcionamento com confirmação", "it" to "Revoca — ripristina il funzionamento con conferma", "ja" to "取り消す — 確認を必須とする動作に戻す", "zh" to "撤回 — 恢复为需确认才能操作", "hi" to "वापस लें — पुष्टि-आधारित संचालन बहाल करें", "ar" to "أبطِل — أعِد التشغيل المشروط بالتأكيد"),
        "mid" to mapOf("en" to "Medical ID", "es" to "Identificación médica", "fr" to "Fiche médicale", "de" to "Notfallpass", "pt" to "Identificação médica", "it" to "Scheda medica", "ja" to "メディカル ID", "zh" to "医疗卡", "hi" to "मेडिकल आईडी", "ar" to "البطاقة الطبية"),
        "mid.issue" to mapOf("en" to "Issue Medical ID", "es" to "Emitir la identificación médica", "fr" to "Émettre la fiche médicale", "de" to "Notfallpass ausstellen", "pt" to "Emitir a identificação médica", "it" to "Emetti la scheda medica", "ja" to "メディカル ID を発行", "zh" to "签发医疗卡", "hi" to "मेडिकल आईडी जारी करें", "ar" to "أصدر البطاقة الطبية"),
        "mid.sub" to mapOf("en" to "A shareable card for first responders: condition-level facts only, readable from a locked phone. Re-issuing rotates the QR and kills the old one.", "es" to "Una tarjeta compartible para el personal de emergencias: solo datos de nivel clínico, legible desde un teléfono bloqueado. Volver a emitirla rota el QR y anula el anterior.", "fr" to "Une fiche partageable pour les secouristes : uniquement des faits de niveau clinique, lisible depuis un téléphone verrouillé. La réémettre fait tourner le QR et annule l'ancien.", "de" to "Eine teilbare Karte für Ersthelfer: nur Angaben auf Befundebene, vom gesperrten Telefon lesbar. Ein erneutes Ausstellen wechselt den QR-Code und macht den alten ungültig.", "pt" to "Um cartão partilhável para os primeiros socorros: apenas factos de nível clínico, legível a partir de um telefone bloqueado. Reemitir roda o QR e anula o anterior.", "it" to "Una scheda condivisibile per i soccorritori: solo dati di livello clinico, leggibile da un telefono bloccato. Riemetterla ruota il QR e annulla il precedente.", "ja" to "救急対応者に渡せるカードです。記載は病態レベルの事実のみで、ロックされた端末からでも読めます。再発行すると QR が更新され、古いものは無効になります。", "zh" to "一张可交给急救人员的卡片：只含病情层面的事实，锁屏状态下也能读取。重新签发会更换二维码并作废旧的。", "hi" to "प्राथमिक उत्तरदाताओं के लिए साझा किया जा सकने वाला कार्ड: केवल स्थिति-स्तर के तथ्य, लॉक फ़ोन से भी पढ़ने योग्य। दोबारा जारी करने पर QR बदल जाता है और पुराना रद्द हो जाता है।", "ar" to "بطاقة يمكن مشاركتها مع المسعفين: حقائق على مستوى الحالة فقط، وتُقرأ من هاتف مقفل. وإعادة الإصدار تُبدّل رمز الاستجابة وتُبطل القديم."),
        "mid.rotate" to mapOf("en" to "Rotate QR", "es" to "Rotar el QR", "fr" to "Renouveler le QR", "de" to "QR wechseln", "pt" to "Rodar o QR", "it" to "Ruota il QR", "ja" to "QR を更新", "zh" to "更换二维码", "hi" to "QR बदलें", "ar" to "بدّل رمز الاستجابة"),
        "mid.revoke" to mapOf("en" to "Revoke card", "es" to "Revocar la tarjeta", "fr" to "Révoquer la fiche", "de" to "Karte widerrufen", "pt" to "Revogar o cartão", "it" to "Revoca la scheda", "ja" to "カードを失効させる", "zh" to "吊销卡片", "hi" to "कार्ड रद्द करें", "ar" to "أبطِل البطاقة"),
        "mid.issued" to mapOf("en" to "Card issued", "es" to "Tarjeta emitida", "fr" to "Fiche émise", "de" to "Karte ausgestellt", "pt" to "Cartão emitido", "it" to "Scheda emessa", "ja" to "カードを発行しました", "zh" to "卡片已签发", "hi" to "कार्ड जारी हुआ", "ar" to "صدرت البطاقة"),
        "mid.responder" to mapOf("en" to "What a responder sees", "es" to "Lo que ve el personal de emergencias", "fr" to "Ce que voit un secouriste", "de" to "Was ein Ersthelfer sieht", "pt" to "O que vê quem socorre", "it" to "Cosa vede un soccorritore", "ja" to "救急対応者に見えるもの", "zh" to "急救人员看到的内容", "hi" to "उत्तरदाता को क्या दिखता है", "ar" to "ما يراه المسعف"),
        "mid.print" to mapOf("en" to "Print or lock-screen the QR at:", "es" to "Imprime el QR o ponlo en la pantalla de bloqueo en:", "fr" to "Imprimez le QR ou mettez-le en écran verrouillé à :", "de" to "Den QR-Code ausdrucken oder auf den Sperrbildschirm legen unter:", "pt" to "Imprima o QR ou coloque-o no ecrã de bloqueio em:", "it" to "Stampa il QR o mettilo nella schermata di blocco su:", "ja" to "QR を印刷するか、ロック画面に設定してください：", "zh" to "在此打印二维码或将其设为锁屏：", "hi" to "QR यहाँ से प्रिंट करें या लॉक-स्क्रीन पर लगाएँ:", "ar" to "اطبع رمز الاستجابة أو ضعه على شاشة القفل من:"),
        "rob.bind" to mapOf("en" to "Bind a robot", "es" to "Vincular un robot", "fr" to "Lier un robot", "de" to "Einen Roboter binden", "pt" to "Vincular um robô", "it" to "Collega un robot", "ja" to "ロボットを結び付ける", "zh" to "绑定一个机器人", "hi" to "एक रोबोट जोड़ें", "ar" to "اربط آليًا"),
        "rob.sub" to mapOf("en" to "Bound robots respond to escalations: mobile bodies come to you; vacuums dock and clear the floor.", "es" to "Los robots vinculados responden a las escaladas: los cuerpos móviles acuden a ti; las aspiradoras se acoplan y despejan el suelo.", "fr" to "Les robots liés répondent aux escalades : les corps mobiles viennent à vous ; les aspirateurs se remettent en base et dégagent le sol.", "de" to "Gebundene Roboter reagieren auf Eskalationen: mobile Körper kommen zu dir, Sauger docken an und räumen den Boden frei.", "pt" to "Os robôs vinculados respondem às escaladas: os corpos móveis vão ter consigo; os aspiradores acoplam e libertam o chão.", "it" to "I robot collegati rispondono alle escalation: i corpi mobili vengono da te; gli aspirapolvere tornano alla base e liberano il pavimento.", "ja" to "結び付けたロボットは段階上昇に応じます。動く身体はあなたのもとへ向かい、掃除機はドックに戻って床を空けます。", "zh" to "已绑定的机器人会响应升级：可移动的躯体会赶到你身边，扫地机则回座并清空地面。", "hi" to "जुड़े हुए रोबोट एस्केलेशन पर प्रतिक्रिया देते हैं: चलने वाले शरीर आपके पास आते हैं; वैक्यूम डॉक पर लौटकर फ़र्श ख़ाली कर देते हैं।", "ar" to "الآليّات المرتبطة تستجيب للتصعيد: الأجسام المتحركة تأتي إليك، والمكانس تعود إلى قواعدها وتُخلي الأرض."),
        "mon" to mapOf("en" to "Live Monitoring", "es" to "Vigilancia en directo", "fr" to "Surveillance en direct", "de" to "Live-Überwachung", "pt" to "Vigilância em direto", "it" to "Monitoraggio dal vivo", "ja" to "ライブ・モニタリング", "zh" to "实时监测", "hi" to "लाइव निगरानी", "ar" to "المراقبة الحيّة"),
        "mon.send" to mapOf("en" to "Send sample", "es" to "Enviar la muestra", "fr" to "Envoyer l'échantillon", "de" to "Probe senden", "pt" to "Enviar a amostra", "it" to "Invia il campione", "ja" to "サンプルを送る", "zh" to "发送样本", "hi" to "नमूना भेजें", "ar" to "أرسِل العيّنة"),
        "mon.person" to mapOf("en" to "Bringing in a person", "es" to "Trayendo a una persona", "fr" to "On fait venir une personne", "de" to "Eine Person wird hinzugezogen", "pt" to "A trazer uma pessoa", "it" to "Sto coinvolgendo una persona", "ja" to "人に入ってもらっています", "zh" to "正在请一位真人介入", "hi" to "किसी व्यक्ति को बुलाया जा रहा है", "ar" to "جارٍ إشراك شخص"),
        "mon.resumes" to mapOf("en" to "Monitoring resumes", "es" to "La vigilancia se reanuda", "fr" to "La surveillance reprend", "de" to "Die Überwachung läuft weiter", "pt" to "A vigilância recomeça", "it" to "Il monitoraggio riprende", "ja" to "モニタリングを再開します", "zh" to "监测已恢复", "hi" to "निगरानी फिर शुरू", "ar" to "تستأنف المراقبة"),
        "cust" to mapOf("en" to "Vault custody", "es" to "Custodia de la bóveda", "fr" to "Garde du coffre", "de" to "Tresor-Verwahrung", "pt" to "Custódia do cofre", "it" to "Custodia della cassaforte", "ja" to "保管庫の管理記録", "zh" to "保险库保管", "hi" to "वॉल्ट अभिरक्षा", "ar" to "حفظ الخزنة"),
        "cust.chain.ok" to mapOf("en" to "🔗 Audit chain intact", "es" to "🔗 Cadena de auditoría intacta", "fr" to "🔗 Chaîne d'audit intacte", "de" to "🔗 Prüfkette unversehrt", "pt" to "🔗 Cadeia de auditoria intacta", "it" to "🔗 Catena di audit intatta", "ja" to "🔗 監査チェーンは無傷です", "zh" to "🔗 审计链完整", "hi" to "🔗 ऑडिट श्रृंखला अक्षुण्ण", "ar" to "🔗 سلسلة التدقيق سليمة"),
        "cust.chain.unknown" to mapOf("en" to "⚠️ Audit chain status unknown", "es" to "⚠️ Estado de la cadena de auditoría desconocido", "fr" to "⚠️ État de la chaîne d'audit inconnu", "de" to "⚠️ Zustand der Prüfkette unbekannt", "pt" to "⚠️ Estado da cadeia de auditoria desconhecido", "it" to "⚠️ Stato della catena di audit sconosciuto", "ja" to "⚠️ 監査チェーンの状態は不明です", "zh" to "⚠️ 审计链状态未知", "hi" to "⚠️ ऑडिट श्रृंखला की स्थिति अज्ञात", "ar" to "⚠️ حالة سلسلة التدقيق غير معروفة"),
        "cust.hash.ok" to mapOf("en" to "Hash chain: intact", "es" to "Cadena de hash: intacta", "fr" to "Chaîne d'empreintes : intacte", "de" to "Hash-Kette: unversehrt", "pt" to "Cadeia de hash: intacta", "it" to "Catena di hash: intatta", "ja" to "ハッシュ連鎖：無傷", "zh" to "哈希链：完整", "hi" to "हैश श्रृंखला: अक्षुण्ण", "ar" to "سلسلة التجزئة: سليمة"),
        "cust.hash.unknown" to mapOf("en" to "Hash chain: unknown", "es" to "Cadena de hash: desconocida", "fr" to "Chaîne d'empreintes : inconnue", "de" to "Hash-Kette: unbekannt", "pt" to "Cadeia de hash: desconhecida", "it" to "Catena di hash: sconosciuta", "ja" to "ハッシュ連鎖：不明", "zh" to "哈希链：未知", "hi" to "हैश श्रृंखला: अज्ञात", "ar" to "سلسلة التجزئة: غير معروفة"),
        "action.update" to mapOf("en" to "Update", "es" to "Actualizar", "fr" to "Mettre à jour", "de" to "Aktualisieren", "pt" to "Atualizar", "it" to "Aggiorna", "ja" to "更新する", "zh" to "更新", "hi" to "अपडेट करें", "ar" to "حدّث"),
        "sos.coordinating" to mapOf("en" to "Coordinating…", "es" to "Coordinando…", "fr" to "Coordination…", "de" to "Wird koordiniert …", "pt" to "A coordenar…", "it" to "Coordinamento…", "ja" to "調整しています…", "zh" to "正在协调…", "hi" to "समन्वय हो रहा है…", "ar" to "جارٍ التنسيق…"),
        "rob.cpr_rated" to mapOf("en" to "CPR-rated", "es" to "homologado para RCP", "fr" to "habilité RCP", "de" to "für Reanimation zugelassen", "pt" to "homologado para RCP", "it" to "abilitato alla RCP", "ja" to "心肺蘇生対応", "zh" to "具备心肺复苏资质", "hi" to "सीपीआर-सक्षम", "ar" to "مؤهَّل للإنعاش"),
        "alarm.lead.short" to mapOf("en" to "Alarms", "es" to "Alarmas", "fr" to "Alertes", "de" to "Alarme", "pt" to "Alarmes", "it" to "Allarmi", "ja" to "アラーム", "zh" to "警报", "hi" to "अलार्म", "ar" to "الإنذارات"),
        "cw.short" to mapOf("en" to "Crash", "es" to "Caídas", "fr" to "Chute", "de" to "Sturz", "pt" to "Queda", "it" to "Caduta", "ja" to "転倒", "zh" to "跌倒", "hi" to "गिरना", "ar" to "السقوط"),
        "mid.short" to mapOf("en" to "Med ID", "es" to "Ficha médica", "fr" to "Fiche méd.", "de" to "Notfallpass", "pt" to "Ficha méd.", "it" to "Scheda med.", "ja" to "医療 ID", "zh" to "医疗卡", "hi" to "मेड आईडी", "ar" to "البطاقة الطبية"),
        "cw.policy" to mapOf("en" to "Policy", "es" to "Política", "fr" to "Règles", "de" to "Regeln", "pt" to "Política", "it" to "Regole", "ja" to "方針", "zh" to "策略", "hi" to "नीति", "ar" to "السياسة"),
        "rob.short" to mapOf("en" to "Robots", "es" to "Robots", "fr" to "Robots", "de" to "Roboter", "pt" to "Robôs", "it" to "Robot", "ja" to "ロボット", "zh" to "机器人", "hi" to "रोबोट", "ar" to "الآليّات"),
        "ns.pr" to mapOf("en" to "When something breaks", "es" to "Cuando algo falla", "fr" to "Quand quelque chose casse", "de" to "Wenn etwas kaputtgeht", "pt" to "Quando algo falha", "it" to "Quando qualcosa si rompe", "ja" to "何かが壊れたとき", "zh" to "出问题的时候", "hi" to "जब कुछ टूटे", "ar" to "حين يتعطّل شيء"),
        "ns.pr.explain" to mapOf("en" to "This app can send a count of what failed — the operation and the HTTP status, the day it happened, and how many times. Not what you typed, not who you are, not which profile. Nothing that identifies you or anyone else.", "es" to "Esta app puede enviar un recuento de lo que falló: la operación y el estado HTTP, el día en que ocurrió y cuántas veces. No lo que escribiste, no quién eres, no qué perfil. Nada que te identifique a ti ni a nadie.", "fr" to "Cette application peut envoyer un décompte de ce qui a échoué : l'opération et le statut HTTP, le jour où c'est arrivé, et combien de fois. Pas ce que vous avez saisi, pas qui vous êtes, pas quel profil. Rien qui vous identifie, ni personne d'autre.", "de" to "Diese App kann eine Zählung des Fehlgeschlagenen senden — den Vorgang und den HTTP-Status, den Tag und wie oft. Nicht, was du getippt hast, nicht, wer du bist, nicht, welches Profil. Nichts, was dich oder sonst jemanden identifiziert.", "pt" to "Esta aplicação pode enviar uma contagem do que falhou: a operação e o estado HTTP, o dia em que aconteceu e quantas vezes. Não o que escreveu, não quem é, não qual perfil. Nada que o identifique a si nem a ninguém.", "it" to "Questa app può inviare un conteggio di ciò che è fallito: l'operazione e lo stato HTTP, il giorno in cui è accaduto e quante volte. Non ciò che hai scritto, non chi sei, non quale profilo. Nulla che identifichi te o chiunque altro.", "ja" to "このアプリは、失敗の件数を送ることができます — 操作と HTTP ステータス、起きた日、そして回数です。入力した内容も、あなたが誰かも、どのプロフィールかも送りません。あなたや他の誰かを特定するものは何も含みません。", "zh" to "这个应用可以发送失败的计数 — 操作与 HTTP 状态、发生的日期、以及次数。不包括你输入的内容、你是谁、用的哪个资料。没有任何能指认你或别人的东西。", "hi" to "यह ऐप विफलताओं की गिनती भेज सकता है — कौन-सा कार्य और HTTP स्थिति, किस दिन हुआ, और कितनी बार। आपने क्या लिखा, आप कौन हैं, कौन-सी प्रोफ़ाइल — ये नहीं। कुछ भी ऐसा नहीं जो आपकी या किसी की पहचान बताए।", "ar" to "يمكن لهذا التطبيق أن يرسل عددًا لما أخفق — العملية وحالة HTTP، واليوم الذي وقع فيه، وكم مرة. لا ما كتبته، ولا من أنت، ولا أي ملف. لا شيء يعرّفك أو يعرّف أحدًا غيرك."),
        "ns.pr.nowhere" to mapOf("en" to "This build reports nowhere. Failures are counted on this device and never leave it.", "es" to "Esta compilación no informa a ninguna parte. Los fallos se cuentan en este dispositivo y nunca salen de él.", "fr" to "Cette version ne signale rien nulle part. Les échecs sont comptés sur cet appareil et n'en sortent jamais.", "de" to "Dieser Build meldet nirgendwohin. Fehler werden auf diesem Gerät gezählt und verlassen es nie.", "pt" to "Esta compilação não reporta a lado nenhum. As falhas são contadas neste dispositivo e nunca saem dele.", "it" to "Questa build non segnala da nessuna parte. Gli errori sono contati su questo dispositivo e non lo lasciano mai.", "ja" to "このビルドはどこにも報告しません。失敗はこの端末で数えられ、端末の外に出ることはありません。", "zh" to "这个版本不向任何地方上报。失败只在本机计数，永远不会离开这台设备。", "hi" to "यह बिल्ड कहीं रिपोर्ट नहीं करता। विफलताएँ इसी डिवाइस पर गिनी जाती हैं और कभी बाहर नहीं जातीं।", "ar" to "هذه النسخة لا ترسل تقارير إلى أي جهة. تُحصى الإخفاقات على هذا الجهاز ولا تغادره أبدًا."),
        "ns.pr.owed" to mapOf("en" to "Nothing is owed. Either nothing has failed, or everything that has was already reported.", "es" to "No hay nada pendiente. O no ha fallado nada, o todo lo que falló ya se informó.", "fr" to "Rien n'est dû. Soit rien n'a échoué, soit tout ce qui a échoué a déjà été signalé.", "de" to "Es steht nichts aus. Entweder ist nichts fehlgeschlagen, oder alles Fehlgeschlagene wurde bereits gemeldet.", "pt" to "Não há nada em dívida. Ou nada falhou, ou tudo o que falhou já foi reportado.", "it" to "Non c'è nulla in sospeso. O non è fallito nulla, o tutto ciò che è fallito è già stato segnalato.", "ja" to "送るべきものはありません。何も失敗していないか、失敗したものはすべて報告済みです。", "zh" to "没有待发送的内容。要么什么都没失败，要么失败过的都已上报。", "hi" to "कुछ भी बकाया नहीं है। या तो कुछ विफल नहीं हुआ, या जो हुआ वह पहले ही भेजा जा चुका है।", "ar" to "لا شيء معلّق. إما أن شيئًا لم يخفق، وإما أن كل ما أخفق قد أُبلغ عنه سلفًا."),
        "ns.pr.send" to mapOf("en" to "Send counts", "es" to "Enviar los recuentos", "fr" to "Envoyer les décomptes", "de" to "Zählungen senden", "pt" to "Enviar as contagens", "it" to "Invia i conteggi", "ja" to "件数を送る", "zh" to "发送计数", "hi" to "गिनती भेजें", "ar" to "أرسل الأعداد"),
        "ns.pr.dont" to mapOf("en" to "Do not send", "es" to "No enviar", "fr" to "Ne pas envoyer", "de" to "Nicht senden", "pt" to "Não enviar", "it" to "Non inviare", "ja" to "送らない", "zh" to "不要发送", "hi" to "मत भेजें", "ar" to "لا ترسل"),
        "ns.pr.toggle" to mapOf("en" to "Send failure counts", "es" to "Enviar recuentos de fallos", "fr" to "Envoyer les décomptes d'échecs", "de" to "Fehlerzählungen senden", "pt" to "Enviar contagens de falhas", "it" to "Invia i conteggi degli errori", "ja" to "失敗の件数を送る", "zh" to "发送失败计数", "hi" to "विफलताओं की गिनती भेजें", "ar" to "أرسل أعداد الإخفاقات"),
        "ns.pr.show" to mapOf("en" to "Show what would be sent", "es" to "Mostrar lo que se enviaría", "fr" to "Montrer ce qui serait envoyé", "de" to "Zeigen, was gesendet würde", "pt" to "Mostrar o que seria enviado", "it" to "Mostra ciò che verrebbe inviato", "ja" to "送られる内容を表示", "zh" to "查看将要发送的内容", "hi" to "जो भेजा जाएगा वह दिखाएँ", "ar" to "أظهر ما سيُرسل"),
        "ns.pr.hide" to mapOf("en" to "Hide what would be sent", "es" to "Ocultar lo que se enviaría", "fr" to "Masquer ce qui serait envoyé", "de" to "Verbergen, was gesendet würde", "pt" to "Ocultar o que seria enviado", "it" to "Nascondi ciò che verrebbe inviato", "ja" to "送られる内容を隠す", "zh" to "隐藏将要发送的内容", "hi" to "जो भेजा जाएगा वह छिपाएँ", "ar" to "أخفِ ما سيُرسل"),
        "alarm.tripped" to mapOf("en" to "The crash watch tripped: {name} was contacted. Any normal reading stands it down.", "es" to "La vigilancia de caídas se activó: se contactó a {name}. Cualquier lectura normal la desactiva.", "fr" to "La veille d'accident s'est déclenchée : {name} a été contacté. Toute mesure normale la désarme.", "de" to "Die Sturzwache hat ausgelöst: {name} wurde benachrichtigt. Jeder normale Messwert setzt sie zurück.", "pt" to "A vigilância de queda disparou: {name} foi contactado. Qualquer leitura normal desativa-a.", "it" to "La sorveglianza incidenti è scattata: {name} è stato contattato. Qualsiasi misurazione normale la disattiva.", "ja" to "クラッシュウォッチが作動しました：{name} に連絡しました。通常の測定値が届けば解除されます。", "zh" to "跌倒守护已触发：已联系 {name}。任何正常读数都会将其解除。", "hi" to "क्रैश वॉच सक्रिय हो गई: {name} से संपर्क किया गया। कोई भी सामान्य रीडिंग इसे बंद कर देती है।", "ar" to "تم تفعيل مراقبة الحوادث: جرى الاتصال بـ {name}. وأي قراءة طبيعية تُلغيها."),
        "alarm.armed" to mapOf("en" to "Armed — {name} will be contacted after {n} unanswered attempts.", "es" to "Activada — se contactará a {name} tras {n} intentos sin respuesta.", "fr" to "Armée — {name} sera contacté après {n} tentatives sans réponse.", "de" to "Scharf — {name} wird nach {n} unbeantworteten Versuchen benachrichtigt.", "pt" to "Armada — {name} será contactado após {n} tentativas sem resposta.", "it" to "Attiva — {name} verrà contattato dopo {n} tentativi senza risposta.", "ja" to "作動中 — 応答のない確認が {n} 回続くと {name} に連絡します。", "zh" to "已启用 — 在 {n} 次无人应答后将联系 {name}。", "hi" to "सक्रिय — {n} बार उत्तर न मिलने पर {name} से संपर्क किया जाएगा।", "ar" to "مُفعَّلة — سيجري الاتصال بـ {name} بعد {n} محاولات دون رد."),
        "alarm.ems" to mapOf("en" to "May request emergency services (relayed as a request — this app cannot itself place a call)", "es" to "Puede solicitar servicios de emergencia (se transmite como una solicitud — esta app no puede llamar por sí misma)", "fr" to "Peut demander les services d'urgence (transmis comme une demande — cette application ne peut pas passer d'appel elle-même)", "de" to "Darf Rettungsdienste anfordern (als Anfrage weitergeleitet — diese App kann selbst nicht anrufen)", "pt" to "Pode pedir serviços de emergência (transmitido como um pedido — esta aplicação não pode fazer chamadas)", "it" to "Può richiedere i servizi di emergenza (inoltrato come richiesta — questa app non può effettuare chiamate)", "ja" to "緊急サービスの要請を許可する（要請として転送されます。このアプリ自体は通報できません）", "zh" to "可以请求紧急服务（以请求的形式转达 — 本应用本身无法拨打电话）", "hi" to "आपातकालीन सेवाओं का अनुरोध कर सकता है (अनुरोध के रूप में भेजा जाता है — यह ऐप स्वयं कॉल नहीं कर सकता)", "ar" to "قد يطلب خدمات الطوارئ (يُنقل بوصفه طلبًا — لا يمكن لهذا التطبيق إجراء مكالمة بنفسه)"),
        "offline.title" to mapOf("en" to "What this deployment can reach", "es" to "Qué puede alcanzar esta instalación", "fr" to "Ce que ce déploiement peut atteindre", "de" to "Was diese Installation erreichen kann", "pt" to "O que esta instalação pode alcançar", "it" to "Cosa può raggiungere questa installazione", "ja" to "この環境が接続できる範囲", "zh" to "此部署可以连接到什么", "hi" to "यह परिनियोजन किस तक पहुँच सकता है", "ar" to "ما يمكن أن يصل إليه هذا النشر"),
        "offline.on" to mapOf("en" to "Offline — nothing leaves this machine", "es" to "Sin conexión — nada sale de esta máquina", "fr" to "Hors ligne — rien ne quitte cette machine", "de" to "Offline — nichts verlässt diesen Rechner", "pt" to "Offline — nada sai desta máquina", "it" to "Offline — nulla esce da questa macchina", "ja" to "オフライン — このマシンから何も出ません", "zh" to "离线 — 任何内容都不会离开这台机器", "hi" to "ऑफ़लाइन — इस मशीन से कुछ भी बाहर नहीं जाता", "ar" to "دون اتصال — لا شيء يغادر هذا الجهاز"),
        "offline.off" to mapOf("en" to "Online — this deployment can reach other machines", "es" to "En línea — esta instalación puede alcanzar otras máquinas", "fr" to "En ligne — ce déploiement peut atteindre d’autres machines", "de" to "Online — diese Installation kann andere Rechner erreichen", "pt" to "Online — esta instalação pode alcançar outras máquinas", "it" to "Online — questa installazione può raggiungere altre macchine", "ja" to "オンライン — この環境は他のマシンに接続できます", "zh" to "在线 — 此部署可以连接其他机器", "hi" to "ऑनलाइन — यह परिनियोजन अन्य मशीनों तक पहुँच सकता है", "ar" to "متصل — يمكن لهذا النشر الوصول إلى أجهزة أخرى"),
        "tab.overview" to mapOf(
            "en" to "Overview", "es" to "Resumen", "fr" to "Aperçu",
            "de" to "Übersicht", "pt" to "Visão geral", "it" to "Panoramica",
            "ja" to "概要", "zh" to "概览", "hi" to "अवलोकन", "ar" to "نظرة عامة"),
        "self.profile_id" to mapOf("en" to "prf_…", "es" to "prf_…", "fr" to "prf_…", "de" to "prf_…", "pt" to "prf_…", "it" to "prf_…", "ja" to "prf_…", "zh" to "prf_…", "hi" to "prf_…", "ar" to "prf_…"),
        "self.title" to mapOf("en" to "Your own profile", "es" to "Tu propio perfil", "fr" to "Votre propre profil", "de" to "Ihr eigenes Profil", "pt" to "O seu próprio perfil", "it" to "Il tuo profilo", "ja" to "あなた自身のプロフィール", "zh" to "你自己的档案", "hi" to "आपकी अपनी प्रोफ़ाइल", "ar" to "ملفك الشخصي"),
        "self.lead" to mapOf("en" to "The QRME profile that speaks as you. The Guardian tells it nothing until you say which parts it may pass on, and you can see exactly what would go before any of it does.", "es" to "El perfil de QRME que habla como tú. El Guardián no le cuenta nada hasta que digas qué partes puede transmitir, y puedes ver exactamente qué se enviaría antes de que se envíe.", "fr" to "Le profil QRME qui parle en votre nom. Le Gardien ne lui dit rien tant que vous n’avez pas indiqué ce qu’il peut transmettre, et vous voyez exactement ce qui partirait avant que quoi que ce soit parte.", "de" to "Das QRME-Profil, das als Sie spricht. Der Guardian sagt ihm nichts, bis Sie festlegen, was er weitergeben darf, und Sie sehen genau, was ginge, bevor irgendetwas geht.", "pt" to "O perfil QRME que fala como você. O Guardião não lhe conta nada até dizer que partes pode transmitir, e vê exatamente o que iria antes de qualquer coisa ir.", "it" to "Il profilo QRME che parla come te. Il Guardian non gli dice nulla finché non indichi cosa può trasmettere, e vedi esattamente cosa partirebbe prima che parta.", "ja" to "あなたとして話す QRME のプロフィールです。どの部分を伝えてよいか決めるまで、ガーディアンは何も伝えません。送られる内容は送信前にそのまま確認できます。", "zh" to "以你的身份说话的 QRME 档案。在你指明可以转达哪些部分之前，守护者不会告诉它任何事，而且发送前你能看到确切会送出什么。", "hi" to "वह QRME प्रोफ़ाइल जो आपके रूप में बोलती है। जब तक आप यह न बताएँ कि कौन-से हिस्से भेजे जा सकते हैं, गार्जियन उसे कुछ नहीं बताता, और भेजे जाने से पहले आप ठीक-ठीक देख सकते हैं कि क्या जाएगा।", "ar" to "ملف QRME الذي يتحدث بصفتك. لا يخبره الحارس بشيء حتى تحدد ما يمكن نقله، ويمكنك أن ترى بالضبط ما سيُرسل قبل أن يُرسل أي شيء."),
        "self.link" to mapOf("en" to "Link it", "es" to "Vincúlalo", "fr" to "Le relier", "de" to "Verknüpfen", "pt" to "Ligar", "it" to "Collegalo", "ja" to "リンクする", "zh" to "关联它", "hi" to "इसे जोड़ें", "ar" to "اربطه"),
        "self.paste" to mapOf("en" to "Paste the profile's id and your owner token from QRME. It has to be a profile QRME calls your own — a made-up one will be refused.", "es" to "Pega el id del perfil y tu token de propietario de QRME. Tiene que ser un perfil que QRME considere tuyo; uno inventado será rechazado.", "fr" to "Collez l’identifiant du profil et votre jeton de propriétaire QRME. Ce doit être un profil que QRME reconnaît comme le vôtre ; un profil inventé sera refusé.", "de" to "Fügen Sie die Profil-ID und Ihr Eigentümer-Token aus QRME ein. Es muss ein Profil sein, das QRME als Ihr eigenes führt — ein erfundenes wird abgelehnt.", "pt" to "Cole o id do perfil e o seu token de proprietário do QRME. Tem de ser um perfil que o QRME considere seu — um inventado será recusado.", "it" to "Incolla l’id del profilo e il tuo token di proprietario da QRME. Deve essere un profilo che QRME riconosce come tuo — uno inventato verrà rifiutato.", "ja" to "QRME のプロフィール ID と所有者トークンを貼り付けてください。QRME があなた自身のものと認めるプロフィールに限られ、架空のものは拒否されます。", "zh" to "粘贴档案 id 和你在 QRME 的所有者令牌。必须是 QRME 认定属于你自己的档案 — 编造的会被拒绝。", "hi" to "QRME से प्रोफ़ाइल का id और अपना स्वामी टोकन चिपकाएँ। यह ऐसी प्रोफ़ाइल होनी चाहिए जिसे QRME आपकी अपनी मानता हो — बनावटी को अस्वीकार कर दिया जाएगा।", "ar" to "الصق معرِّف الملف ورمز المالك الخاص بك من QRME. يجب أن يكون ملفًا يعتبره QRME ملكك — وسيُرفض أي ملف مُختلق."),
        "self.owner_token" to mapOf("en" to "owner token", "es" to "token de propietario", "fr" to "jeton de propriétaire", "de" to "Eigentümer-Token", "pt" to "token de proprietário", "it" to "token di proprietario", "ja" to "所有者トークン", "zh" to "所有者令牌", "hi" to "स्वामी टोकन", "ar" to "رمز المالك"),
        "self.link_button" to mapOf("en" to "Link this profile", "es" to "Vincular este perfil", "fr" to "Relier ce profil", "de" to "Dieses Profil verknüpfen", "pt" to "Ligar este perfil", "it" to "Collega questo profilo", "ja" to "このプロフィールをリンク", "zh" to "关联此档案", "hi" to "इस प्रोफ़ाइल को जोड़ें", "ar" to "اربط هذا الملف"),
        "self.may_know" to mapOf("en" to "What it may know", "es" to "Qué puede saber", "fr" to "Ce qu’il peut savoir", "de" to "Was es wissen darf", "pt" to "O que pode saber", "it" to "Cosa può sapere", "ja" to "伝えてよいこと", "zh" to "它可以知道什么", "hi" to "यह क्या जान सकता है", "ar" to "ما يمكن أن يعرفه"),
        "self.until_tick" to mapOf("en" to "Nothing is passed on until you tick it.", "es" to "No se transmite nada hasta que lo marques.", "fr" to "Rien n’est transmis tant que vous ne l’avez pas coché.", "de" to "Nichts wird weitergegeben, bis Sie es ankreuzen.", "pt" to "Nada é transmitido até o marcar.", "it" to "Non viene trasmesso nulla finché non lo spunti.", "ja" to "チェックするまで何も伝えられません。", "zh" to "在你勾选之前，不会转达任何内容。", "hi" to "जब तक आप चुनें नहीं, कुछ भी नहीं भेजा जाता।", "ar" to "لا يُنقل شيء حتى تحدده."),
        "self.exactly" to mapOf("en" to "Exactly what would be sent", "es" to "Exactamente lo que se enviaría", "fr" to "Exactement ce qui serait envoyé", "de" to "Genau das, was gesendet würde", "pt" to "Exatamente o que seria enviado", "it" to "Esattamente ciò che verrebbe inviato", "ja" to "送られる内容そのもの", "zh" to "确切会发送的内容", "hi" to "ठीक वही जो भेजा जाएगा", "ar" to "ما سيُرسل بالضبط"),
        "self.nothing_ticked" to mapOf("en" to "Nothing, because nothing is ticked.", "es" to "Nada, porque no hay nada marcado.", "fr" to "Rien, parce que rien n’est coché.", "de" to "Nichts, weil nichts angekreuzt ist.", "pt" to "Nada, porque nada está marcado.", "it" to "Niente, perché non è spuntato nulla.", "ja" to "何もチェックされていないため、何もありません。", "zh" to "没有内容，因为没有勾选任何项。", "hi" to "कुछ नहीं, क्योंकि कुछ चुना नहीं गया है।", "ar" to "لا شيء، لأنه لم يتم تحديد أي شيء."),
        "self.message_itself" to mapOf("en" to "This is the message itself, not a description of it. Medication is the one part made of your own words, so it shows the names as you typed them.", "es" to "Este es el mensaje en sí, no una descripción. La medicación es la única parte hecha con tus propias palabras, así que muestra los nombres tal como los escribiste.", "fr" to "Ceci est le message lui-même, pas sa description. Les médicaments sont la seule partie faite de vos propres mots : les noms s’affichent tels que vous les avez saisis.", "de" to "Dies ist die Nachricht selbst, keine Beschreibung. Die Medikation ist der einzige Teil aus Ihren eigenen Worten, daher erscheinen die Namen so, wie Sie sie eingegeben haben.", "pt" to "Esta é a mensagem em si, não uma descrição. A medicação é a única parte feita das suas próprias palavras, por isso mostra os nomes tal como os escreveu.", "it" to "Questo è il messaggio stesso, non una sua descrizione. I farmaci sono l’unica parte fatta di parole tue, quindi i nomi appaiono come li hai scritti.", "ja" to "これは説明ではなく、メッセージそのものです。薬だけはご自身の言葉でできているため、入力したとおりの名称が表示されます。", "zh" to "这就是消息本身，而不是对它的描述。用药是唯一由你自己的措辞构成的部分，因此名称按你输入的原样显示。", "hi" to "यह संदेश स्वयं है, उसका विवरण नहीं। दवा ही एकमात्र हिस्सा है जो आपके अपने शब्दों से बना है, इसलिए नाम वैसे ही दिखते हैं जैसे आपने लिखे।", "ar" to "هذه هي الرسالة نفسها، لا وصفٌ لها. الدواء هو الجزء الوحيد المكوَّن من كلماتك، لذا تظهر الأسماء كما كتبتها."),
        "self.send" to mapOf("en" to "Send this to my profile", "es" to "Enviar esto a mi perfil", "fr" to "Envoyer ceci à mon profil", "de" to "Dies an mein Profil senden", "pt" to "Enviar isto ao meu perfil", "it" to "Invia questo al mio profilo", "ja" to "これを自分のプロフィールに送る", "zh" to "把这个发送到我的档案", "hi" to "इसे मेरी प्रोफ़ाइल को भेजें", "ar" to "أرسل هذا إلى ملفي"),
        "self.stop" to mapOf("en" to "Stop", "es" to "Detener", "fr" to "Arrêter", "de" to "Beenden", "pt" to "Parar", "it" to "Ferma", "ja" to "やめる", "zh" to "停止", "hi" to "रोकें", "ar" to "إيقاف"),
        "self.unlink_note" to mapOf("en" to "Unlinking removes the token and everything you ticked. What the profile was already told stays in its own source list, in QRME, where you can delete it.", "es" to "Desvincular elimina el token y todo lo que marcaste. Lo que ya se le dijo al perfil permanece en su propia lista de fuentes, en QRME, donde puedes borrarlo.", "fr" to "Le fait de délier supprime le jeton et tout ce que vous aviez coché. Ce qui a déjà été dit au profil reste dans sa liste de sources, dans QRME, où vous pouvez le supprimer.", "de" to "Das Trennen entfernt das Token und alles, was Sie angekreuzt hatten. Was dem Profil bereits mitgeteilt wurde, bleibt in dessen Quellenliste in QRME, wo Sie es löschen können.", "pt" to "Desligar remove o token e tudo o que marcou. O que já foi dito ao perfil fica na sua própria lista de fontes, no QRME, onde o pode apagar.", "it" to "Scollegare rimuove il token e tutto ciò che avevi spuntato. Quanto già detto al profilo resta nel suo elenco di fonti, in QRME, dove puoi eliminarlo.", "ja" to "リンクを解除するとトークンとチェックした内容がすべて削除されます。すでにプロフィールに伝えた内容は QRME のソース一覧に残り、そこで削除できます。", "zh" to "取消关联会移除令牌和你勾选的全部内容。已经告诉档案的内容仍留在 QRME 的来源列表中，你可以在那里删除。", "hi" to "अनलिंक करने से टोकन और आपके चुने हुए सब कुछ हट जाता है। प्रोफ़ाइल को पहले जो बताया जा चुका है वह QRME की उसकी स्रोत सूची में रहता है, जहाँ आप उसे मिटा सकते हैं।", "ar" to "يؤدي إلغاء الربط إلى إزالة الرمز وكل ما حددته. ويبقى ما قيل للملف سابقًا في قائمة مصادره داخل QRME، حيث يمكنك حذفه."),
        "self.unlink" to mapOf("en" to "Unlink", "es" to "Desvincular", "fr" to "Délier", "de" to "Trennen", "pt" to "Desligar", "it" to "Scollega", "ja" to "リンク解除", "zh" to "取消关联", "hi" to "अनलिंक करें", "ar" to "إلغاء الربط"),
        "self.linked_note" to mapOf("en" to "Linked. Nothing is shared yet.", "es" to "Vinculado. Todavía no se comparte nada.", "fr" to "Relié. Rien n’est encore partagé.", "de" to "Verknüpft. Es wird noch nichts geteilt.", "pt" to "Ligado. Ainda não é partilhado nada.", "it" to "Collegato. Non è ancora condiviso nulla.", "ja" to "リンクしました。まだ何も共有されていません。", "zh" to "已关联。尚未共享任何内容。", "hi" to "जुड़ गया। अभी कुछ भी साझा नहीं किया गया।", "ar" to "تم الربط. لم تتم مشاركة أي شيء بعد."),
        "self.saved" to mapOf("en" to "Saved.", "es" to "Guardado.", "fr" to "Enregistré.", "de" to "Gespeichert.", "pt" to "Guardado.", "it" to "Salvato.", "ja" to "保存しました。", "zh" to "已保存。", "hi" to "सहेजा गया।", "ar" to "تم الحفظ."),
        "self.sent" to mapOf("en" to "Sent.", "es" to "Enviado.", "fr" to "Envoyé.", "de" to "Gesendet.", "pt" to "Enviado.", "it" to "Inviato.", "ja" to "送信しました。", "zh" to "已发送。", "hi" to "भेज दिया गया।", "ar" to "تم الإرسال."),
        "self.unlinked" to mapOf("en" to "Unlinked.", "es" to "Desvinculado.", "fr" to "Délié.", "de" to "Getrennt.", "pt" to "Desligado.", "it" to "Scollegato.", "ja" to "リンクを解除しました。", "zh" to "已取消关联。", "hi" to "अनलिंक कर दिया गया।", "ar" to "تم إلغاء الربط."),
        "tab.care" to mapOf(
            "en" to "Care", "es" to "Cuidado", "fr" to "Soins",
            "de" to "Fürsorge", "pt" to "Cuidado", "it" to "Cura",
            "ja" to "ケア", "zh" to "关怀", "hi" to "देखभाल", "ar" to "رعاية"),
        "tab.life" to mapOf(
            "en" to "Life", "es" to "Vida", "fr" to "Vie",
            "de" to "Leben", "pt" to "Vida", "it" to "Vita",
            "ja" to "ライフ", "zh" to "生活", "hi" to "जीवन", "ar" to "الحياة"),
        "tab.safety" to mapOf(
            "en" to "Safety", "es" to "Seguridad", "fr" to "Sécurité",
            "de" to "Sicherheit", "pt" to "Segurança", "it" to "Sicurezza",
            "ja" to "安全", "zh" to "安全", "hi" to "सुरक्षा", "ar" to "السلامة"),
        "tab.connect" to mapOf(
            "en" to "Connect", "es" to "Conectar", "fr" to "Connecter",
            "de" to "Verbinden", "pt" to "Conectar", "it" to "Connetti",
            "ja" to "接続", "zh" to "连接", "hi" to "कनेक्ट", "ar" to "اتصال"),
            "en" to "Send", "es" to "Enviar", "fr" to "Envoyer",
            "de" to "Senden", "pt" to "Enviar", "it" to "Invia",
            "ja" to "送信", "zh" to "发送", "hi" to "भेजें", "ar" to "إرسال"),
            "en" to "Save", "es" to "Guardar", "fr" to "Enregistrer",
            "de" to "Speichern", "pt" to "Salvar", "it" to "Salva",
            "ja" to "保存", "zh" to "保存", "hi" to "सहेजें", "ar" to "حفظ"),
            "en" to "Translate", "es" to "Traducir", "fr" to "Traduire",
            "de" to "Übersetzen", "pt" to "Traduzir", "it" to "Traduci",
            "ja" to "翻訳", "zh" to "翻译", "hi" to "अनुवाद", "ar" to "ترجمة"),
        "action.sign_out" to mapOf(
            "en" to "Sign out", "es" to "Cerrar sesión", "fr" to "Se déconnecter",
            "de" to "Abmelden", "pt" to "Sair", "it" to "Esci",
            "ja" to "サインアウト", "zh" to "退出登录", "hi" to "साइन आउट",
            "ar" to "تسجيل الخروج"),
            "en" to "Refresh", "es" to "Actualizar", "fr" to "Actualiser",
            "de" to "Aktualisieren", "pt" to "Atualizar", "it" to "Aggiorna",
            "ja" to "更新", "zh" to "刷新", "hi" to "रीफ़्रेश", "ar" to "تحديث"),
    )
}
