import SwiftUI

/// The parts of a guidance payload beyond the conversational text: the
/// structured first-aid playbook (CPR / AED steps with the pace cue) and the
/// crisis / self-help references — e.g. the 988 Suicide & Crisis Lifeline.
struct GuidanceExtras: View {
    let guidance: Guidance
    @EnvironmentObject var state: AppState

    var body: some View {
        if let who = guidance.specialist {
            HStack(spacing: 8) {
                Image(systemName: "person.text.rectangle")
                    .font(.caption).foregroundStyle(Theme.brandA)
                Text(who).font(.caption.bold()).foregroundStyle(Theme.txt)
                if guidance.source == "tandem" {
                    Text("LIVE · QRME").font(.caption2.bold())
                        .padding(.horizontal, 7).padding(.vertical, 3)
                        .background(Theme.green.opacity(0.16))
                        .foregroundStyle(Theme.green)
                        .clipShape(Capsule())
                }
            }
        }
        if let c = guidance.custody {
            if c.vaulted, let key = c.pdi_key {
                VStack(alignment: .leading, spacing: 1) {
                    Text(L10n.t("fa.sealed", state.language))
                        .font(.caption2.bold()).foregroundStyle(Theme.green)
                    Text(key).font(.caption2).foregroundStyle(Theme.t3)
                        .lineLimit(1).truncationMode(.middle)
                }
            } else if let note = c.note {
                Text("⚠️ \(note)").font(.caption2).foregroundStyle(Theme.amber)
            }
        }
        if let aid = guidance.first_aid {
            VStack(alignment: .leading, spacing: 6) {
                HStack(spacing: 8) {
                    Text(aid.kind.uppercased()).font(.caption2.bold())
                        .padding(.horizontal, 7).padding(.vertical, 3)
                        .background(Theme.red.opacity(0.16)).foregroundStyle(Theme.red)
                        .clipShape(Capsule())
                    Text(L10n.t("fa", state.language))
                        .font(.subheadline.bold()).foregroundStyle(Theme.txt)
                }
                if aid.call_emergency_services == true {
                    Text(L10n.t("fa.call", state.language))
                        .font(.caption.bold()).foregroundStyle(Theme.red)
                }
                ForEach(Array(aid.steps.enumerated()), id: \.offset) { i, step in
                    Text("\(i + 1). \(step)")
                        .font(.footnote).foregroundStyle(Theme.txt)
                }
                if let pace = aid.pace {
                    Divider().overlay(Theme.line)
                    Text(L10n.fill("fa.pace", state.language,
                                   ["cpm": "\(pace.compressions_per_minute)",
                                    "ratio": pace.compression_to_breath_ratio]))
                        .font(.caption.bold()).foregroundStyle(Theme.amber)
                    if let cue = pace.cue {
                        Text("💡 \(cue.light)").font(.caption2).foregroundStyle(Theme.t2)
                        Text("🔊 \(cue.audio)").font(.caption2).foregroundStyle(Theme.t2)
                    }
                }
            }
        }
        if let note = guidance.translation_note {
            Text("🌐 \(note)").font(.caption2).foregroundStyle(Theme.amber)
        }
        if let refs = guidance.references, !refs.isEmpty {
            VStack(alignment: .leading, spacing: 3) {
                ForEach(refs, id: \.self) { r in
                    Text("→ \(r)").font(.caption)
                        .foregroundStyle(r.contains("988") ? Theme.green : Theme.t2)
                }
            }
        }
        if let p = guidance.provenance {
            VStack(alignment: .leading, spacing: 4) {
                Divider().overlay(Theme.line)
                Text(L10n.t("fa.derived", state.language)).font(.caption.bold()).foregroundStyle(Theme.txt)
                ForEach(p.evidence, id: \.url) { e in
                    VStack(alignment: .leading, spacing: 1) {
                        Text("\(e.publisher) — \(e.title)")
                            .font(.caption).foregroundStyle(Theme.txt)
                        if let s = e.supports {
                            Text(L10n.fill("fa.supports", state.language, ["sources": s])).font(.caption2).foregroundStyle(Theme.t2)
                        }
                        Text(e.url).font(.caption2).foregroundStyle(Theme.brandA)
                    }
                }
                Text("\(p.method) · generated by \(p.generated_by)")
                    .font(.caption2).foregroundStyle(Theme.t3)
                Text(p.disclaimer).font(.caption2).foregroundStyle(Theme.t3)
            }
        }
    }
}
