#!/usr/bin/env python3
"""Generate the README's hero art — GENERATED, do not hand-edit the output.

    python3 tools/build_assets.py

These four were hand-built one-offs and aged the way hand-built one-offs do:
drawn before the escalation ceiling, care beacons, the workplace relay, the
family layer's oversight tiers and the robot first-aid roles existed, and still
showing an early product several releases later.

They are generated now, from the same palette constants `docs/screens/build.py`
uses, for the same reason the screens are: a picture of the product that cannot
be regenerated is a picture that will be wrong soon, and nobody will notice.

Dependency-free — stdlib only, so anyone can regenerate without installing
anything.
"""

from __future__ import annotations

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets")

# Straight from docs/screens/build.py, so the art cannot drift from the screens.
C = {
    "scrA": "#0e1626", "scrB": "#0a0f1c",
    "card": "#182238", "card2": "#1f2b45", "line": "#26314e",
    "txt": "#eef1f7", "t2": "#8a94ad", "t3": "#626d88",
    "brandA": "#7c5cff", "brandB": "#3aa0ff",
    "green": "#43e08a", "amber": "#f7b731", "red": "#ff4d5e",
    "emer": "#ff3b30", "cyan": "#38bdf8",
}

W, H = 1280, 640


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def text(x, y, s, size=14, fill=None, weight=400, anchor="start", spacing=0):
    ls = f' letter-spacing="{spacing}"' if spacing else ""
    return (f'<text x="{x}" y="{y}" font-size="{size}" fill="{fill or C["txt"]}"'
            f' font-weight="{weight}" text-anchor="{anchor}"{ls}>{esc(s)}</text>')


def rrect(x, y, w, h, r, fill, stroke=None, sw=1, dash=None):
    st = f' stroke="{stroke}" stroke-width="{sw}"' if stroke else ""
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}"'
            f' fill="{fill}"{st}{da}/>')


def circle(cx, cy, r, fill="none", stroke=None, sw=1, dash=None):
    st = f' stroke="{stroke}" stroke-width="{sw}"' if stroke else ""
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}"{st}{da}/>'


def arrow(x1, y1, x2, y2, tint, sw=1.8, dash=None):
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<path d="M{x1} {y1} L{x2} {y2}" stroke="{tint}"'
            f' stroke-width="{sw}" fill="none" marker-end="url(#ah)"{da}/>')


def panel(x, y, w, h, title, lines, tint, badge=None):
    o = [rrect(x, y, w, h, 16, C["card"], C["line"], 1.2),
         rrect(x, y, 4, h, 2, tint),
         text(x + 20, y + 30, title, 15, C["txt"], 700)]
    for i, ln in enumerate(lines):
        o.append(text(x + 20, y + 54 + i * 20, ln, 12.5, C["t2"]))
    if badge:
        bw = 18 + len(badge) * 6.4
        o.append(rrect(x + w - bw - 14, y + 14, bw, 22, 11,
                       "rgba(255,255,255,0.05)", tint, 1))
        o.append(text(x + w - bw / 2 - 14, y + 29.5, badge, 10.5, tint, 700,
                      "middle"))
    return "".join(o)


def head(title, desc, w=W, h=H):
    return (
        f'<svg role="img" aria-labelledby="t d" xmlns="http://www.w3.org/2000/svg"'
        f' viewBox="0 0 {w} {h}" width="{w}" height="{h}"'
        f' font-family="Helvetica, Arial, sans-serif">'
        f'<title id="t">{esc(title)}</title><desc id="d">{esc(desc)}</desc>'
        f'<defs>'
        f'<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">'
        f'<stop offset="0" stop-color="{C["scrA"]}"/>'
        f'<stop offset="1" stop-color="{C["scrB"]}"/></linearGradient>'
        f'<linearGradient id="brand" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0" stop-color="{C["brandA"]}"/>'
        f'<stop offset="1" stop-color="{C["brandB"]}"/></linearGradient>'
        f'<radialGradient id="glow" cx="50%" cy="50%" r="50%">'
        f'<stop offset="0" stop-color="{C["green"]}" stop-opacity="0.30"/>'
        f'<stop offset="1" stop-color="{C["green"]}" stop-opacity="0"/>'
        f'</radialGradient>'
        f'<marker id="ah" viewBox="0 0 10 10" refX="9" refY="5"'
        f' markerWidth="6" markerHeight="6" orient="auto-start-reverse">'
        f'<path d="M0 0 L10 5 L0 10 z" fill="{C["t3"]}"/></marker>'
        f'</defs>'
        f'<rect width="{w}" height="{h}" fill="url(#bg)"/>')


def wordmark(x, y, name, tagline, sub=None):
    o = [text(x, y, name, 46, C["txt"], 800, spacing=1),
         rrect(x + 2, y + 16, 92, 4, 2, "url(#brand)"),
         text(x, y + 46, tagline, 16, C["t2"])]
    if sub:
        o.append(text(x, y + 70, sub, 13, C["t3"]))
    return "".join(o)


def cover():
    """Monitor → predict → guide → escalate, and the ceiling on the last rung."""
    o = [head("JIM-mini / Guardian — personal guidance for known conditions",
              "JIM-mini: monitor, predict, guide, escalate — with a life layer "
              "and care beacons. Generated by tools/build_assets.py.")]
    o.append(wordmark(86, 92, "JIM-mini",
                      "Monitor · predict · guide · escalate",
                      "…and a printed code that raises whoever is watching"))

    # The ladder is the product. Draw it as one.
    rungs = [("log", C["t3"]), ("guide", C["brandB"]), ("check in", C["cyan"]),
             ("notify contact", C["amber"]), ("emergency services", C["emer"])]
    bx, by = 86, 236
    for i, (label, tint) in enumerate(rungs):
        y = by + i * 54
        o.append(rrect(bx, y, 300, 42, 12, C["card"], C["line"], 1))
        o.append(rrect(bx, y, 4, 42, 2, tint))
        o.append(circle(bx + 30, y + 21, 6, tint))
        o.append(text(bx + 50, y + 26, label, 13.5, C["txt"], 600))
        o.append(text(bx + 286, y + 26, str(i), 12, C["t3"], 700, "end"))

    # The ceiling: the one rule that points down, and who it is for.
    o.append(f'<path d="M{bx + 312} {by + 3 * 54 + 21} L{bx + 372}'
             f' {by + 3 * 54 + 21}" stroke="{C["amber"]}" stroke-width="1.6"'
             f' stroke-dasharray="4 4"/>')
    o.append(text(bx + 382, by + 3 * 54 + 17, "ceiling for an anonymous",
                  12.5, C["amber"], 600))
    o.append(text(bx + 382, by + 3 * 54 + 33, "beacon alarm — a stranger's tap",
                  12.5, C["t2"]))
    o.append(text(bx + 382, by + 3 * 54 + 49, "never dispatches an ambulance",
                  12.5, C["t2"]))

    # What sits around the core.
    o.append(panel(760, 150, 430, 116, "The life layer",
                   ["Consented sources, check-ins, goals, habit",
                    "streaks, journal, and a 24/7 coach across",
                    "six life areas."], C["green"]))
    o.append(panel(760, 288, 430, 116, "Care beacons",
                   ["A printed code on a fridge door or a walker.",
                    "A first name and a button — never a status,",
                    "never a location."], C["brandB"], "NEW"))
    o.append(panel(760, 426, 430, 116, "Family & the relay",
                   ["Oversight sized by age, ending at 18. On a",
                    "site, a roster worked in order until a named",
                    "human accepts."], C["cyan"]))

    o.append(text(86, 596, "Not a medical device. Call your local emergency "
                  "number first — detection can be wrong in both directions.",
                  12.5, C["t3"]))
    o.append("</svg>")
    return "".join(o)


def guardian_tandem():
    """How a signal becomes guidance, and where it stays local."""
    o = [head("Guardian tandem architecture",
              "Wearable signals to the Guardian, optional QRME specialist, "
              "escalation always local. Generated by tools/build_assets.py.")]
    o.append(text(86, 76, "Guardian tandem", 30, C["txt"], 800))
    o.append(text(86, 106, "Signals in, guidance out — and the one path that "
                  "never leaves the deployment.", 14, C["t2"]))

    o.append(panel(86, 168, 250, 120, "Signals",
                   ["Heart rate, motion, context,", "check-ins, journal notes."],
                   C["cyan"]))
    o.append(panel(400, 168, 250, 120, "Guardian",
                   ["Baseline, detection,", "forecast, sensitivity dial."],
                   C["green"]))
    o.append(panel(714, 168, 250, 120, "Guidance",
                   ["Its own engine, or a QRME", "specialist over HTTP."],
                   C["brandB"]))
    o.append(panel(1028, 168, 166, 120, "PDI",
                   ["Sealed, and", "audit-chained."], C["amber"]))

    for x in (336, 650, 964):
        o.append(arrow(x + 8, 228, x + 56, 228, C["t3"]))

    # The line that matters most is the one that does not go out.
    o.append(rrect(400, 372, 564, 96, 16, C["card2"], C["emer"], 1.4))
    o.append(rrect(400, 372, 4, 96, 2, C["emer"]))
    o.append(text(422, 402, "Escalation stays local", 15, C["txt"], 700))
    o.append(text(422, 426, "Crisis handling never routes through a synthetic "
                  "profile, tandem or not —", 12.5, C["t2"]))
    o.append(text(422, 446, "and an anonymous beacon alarm is capped at "
                  "notify_contact.", 12.5, C["t2"]))
    o.append(arrow(524, 296, 524, 364, C["emer"], 1.8, "5 4"))

    o.append(text(86, 540, "Without a QRME endpoint the Guardian answers from "
                  "its own engine; without PDI it keeps its own store.",
                  13, C["t3"]))
    o.append(text(86, 562, "Neither absence degrades safety — the tandem is an "
                  "addition, never a dependency.", 13, C["t3"]))
    o.append("</svg>")
    return "".join(o)


def life_layer():
    """The half of the product that is not an emergency."""
    o = [head("The Guardian life layer",
              "Sources, check-ins, goals, habits, journal and a coach across "
              "six life areas. Generated by tools/build_assets.py.")]
    o.append(text(86, 76, "The life layer", 30, C["txt"], 800))
    o.append(text(86, 106, "Most days are not emergencies. This is what the "
                  "Guardian does on the other ones.", 14, C["t2"]))

    items = [("Consented sources", "wearable · calendar · spending", C["cyan"]),
             ("Check-ins", "mood and energy, in ten seconds", C["green"]),
             ("Smart goals", "progress that survives a bad week", C["brandB"]),
             ("Habit streaks", "logged, never scolded", C["amber"]),
             ("Journal", "private — and it runs the crisis check", C["red"]),
             ("24/7 coach", "six life areas, one conversation", C["brandA"])]
    for i, (title, sub, tint) in enumerate(items):
        x = 86 + (i % 3) * 372
        y = 190 + (i // 3) * 140
        # No per-card consent strapline: six identical lines is a motif that
        # has stopped being read. The footer states it once, where it lands.
        o.append(rrect(x, y, 336, 104, 16, C["card"], C["line"], 1.2))
        o.append(rrect(x, y, 4, 104, 2, tint))
        o.append(circle(x + 36, y + 52, 16, "rgba(255,255,255,0.05)", tint, 1.4))
        o.append(circle(x + 36, y + 52, 5, tint))
        o.append(text(x + 68, y + 46, title, 15, C["txt"], 700))
        o.append(text(x + 68, y + 68, sub, 12.5, C["t2"]))

    o.append(text(86, 566, "Nothing here is read from a source the user has "
                  "not allowed, and every one can be withdrawn.", 13, C["t3"]))
    o.append("</svg>")
    return "".join(o)


def embodiments():
    """Robots as responders, and the line that never moves."""
    o = [head("Robots as guardian responders",
              "Rated first-aid roles, with autonomous resuscitation behind a "
              "signed waiver. Generated by tools/build_assets.py.")]
    o.append(text(86, 76, "Robots as responders", 30, C["txt"], 800))
    o.append(text(86, 106, "A body that can fetch the AED is worth more than a "
                  "notification. Within limits.", 14, C["t2"]))

    o.append(panel(86, 168, 350, 150, "Assist-rated",
                   ["Fetches the AED, coaches the", "playbook aloud, opens the",
                    "door, calls the contact."], C["green"], "ALLOWED"))
    o.append(panel(466, 168, 350, 150, "Perform-rated",
                   ["May deliver compressions —", "only after a person on scene",
                    "confirms."], C["amber"], "GATED"))
    o.append(panel(846, 168, 348, 150, "Autonomous",
                   ["Behind a signed liability", "waiver, and never signable",
                    "for a minor. By anyone."], C["emer"], "LOCKED"))

    o.append(rrect(86, 372, 1108, 92, 16, C["card2"], C["line"], 1.2))
    o.append(rrect(86, 372, 4, 92, 2, C["red"]))
    o.append(text(108, 402, "A robot never delivers the shock", 15, C["txt"], 700))
    o.append(text(108, 428, "The AED decides. Every command a body accepts is "
                  "on a per-kind allowlist, and every one is audited.",
                  12.5, C["t2"]))

    o.append(text(86, 522, "Binding a robot does not hand it judgement — it "
                  "hands it a task list the escalation ladder controls.",
                  13, C["t3"]))
    o.append(text(86, 546, "Unbinding keeps the sealed record: what it saw "
                  "stays the user's, not the manufacturer's.", 13, C["t3"]))
    o.append("</svg>")
    return "".join(o)



# ---------------------------------------------------------------------------
# The tandem diagram.
#
# This block is deliberately **identical in all three repositories** — qrme,
# jim-mini and pdi each ship the same picture of the suite, because there is
# only one suite and three copies that could disagree is exactly the failure
# this replaces. It is self-contained (its own palette, its own header, its own
# arrowheads) and touches nothing above, so a repo whose brand colour differs
# still renders the same diagram. Edit it in one repo, paste it into the other
# two, regenerate.
#
# It replaces a hand-drawn SVG that had gone wrong in the way hand-drawn things
# do: cream background and a serif face while every other asset in every repo
# is night-indigo, and — worse — only two arrows, drawn back when both of them
# pointed into PDI. The gate agent added a third direction and the picture did
# not know.
# ---------------------------------------------------------------------------

TF = {
    "scrA": "#181235", "scrB": "#0c0920",
    "card": "#201a48", "line": "#302a60",
    "txt": "#f2effc", "t2": "#9a93c6", "t3": "#6a6399",
    "qrme": "#9d7bff",     # neon purple
    "jim": "#7bc47f",      # care green
    "pdi": "#38bdf8",      # vault cyan
    "out": "#ffb84d",      # the one link that runs *out* of PDI
    "gw": "#6a6399",       # the gateway's own fan-out, deliberately unbranded
}
TFW, TFH = 1180, 700


def _tf_text(x, y, s, size=13, fill=None, weight=400, anchor="start", sp=0):
    ls = f' letter-spacing="{sp}"' if sp else ""
    return (f'<text x="{x}" y="{y}" font-size="{size}" fill="{fill or TF["txt"]}"'
            f' font-weight="{weight}" text-anchor="{anchor}"{ls}>{esc(s)}</text>')


def _tf_rect(x, y, w, h, r, fill, stroke=None, sw=1.2):
    st = f' stroke="{stroke}" stroke-width="{sw}"' if stroke else ""
    return (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}"'
            f' fill="{fill}"{st}/>')


def _tf_panel(x, y, w, h, title, lines, tint):
    o = [_tf_rect(x, y, w, h, 16, TF["card"], TF["line"]),
         _tf_rect(x, y, 4, h, 2, tint),
         _tf_text(x + 20, y + 32, title, 16, TF["txt"], 700)]
    for i, ln in enumerate(lines):
        o.append(_tf_text(x + 20, y + 58 + i * 21, ln, 12.5, TF["t2"]))
    return "".join(o)


def _tf_arrow(x1, y1, x2, y2, key):
    """Every link is dashed, because every link is optional — a product with
    none of them configured is a product that still runs."""
    return (f'<path d="M{x1} {y1} L{x2} {y2}" stroke="{TF[key]}"'
            f' stroke-width="1.8" fill="none" stroke-dasharray="6 5"'
            f' opacity="0.85" marker-end="url(#tf_{key})"/>')


def tandem_flow() -> str:
    """The suite as it actually stands: four optional HTTP links, one of which
    runs the other way."""
    o = [f'<svg role="img" aria-labelledby="tft tfd"'
         f' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {TFW} {TFH}"'
         f' width="{TFW}" height="{TFH}"'
         f' font-family="Helvetica, Arial, sans-serif">'
         f'<title id="tft">Tandem architecture — qrme, jim-mini and pdi</title>'
         f'<desc id="tfd">A suite gateway over three products. jim-mini asks '
         f'qrme for specialist guidance; jim-mini and qrme seal payloads into '
         f'pdi; and pdi asks qrme for the words its gate agent speaks. Every '
         f'link is optional and runs over public HTTP. Generated by '
         f'tools/build_assets.py.</desc><defs>'
         f'<linearGradient id="tfbg" x1="0" y1="0" x2="1" y2="1">'
         f'<stop offset="0" stop-color="{TF["scrA"]}"/>'
         f'<stop offset="1" stop-color="{TF["scrB"]}"/></linearGradient>']
    # One arrowhead per link colour: a grey head on a coloured line reads as a
    # different link, which is precisely the distinction this diagram exists
    # to make.
    for key in ("qrme", "jim", "pdi", "out", "gw"):
        o.append(f'<marker id="tf_{key}" viewBox="0 0 10 10" refX="9" refY="5"'
                 f' markerWidth="6" markerHeight="6"'
                 f' orient="auto-start-reverse">'
                 f'<path d="M0 0 L10 5 L0 10 z" fill="{TF[key]}"/></marker>')
    o.append(f'</defs><rect width="{TFW}" height="{TFH}" fill="url(#tfbg)"/>')

    o.append(_tf_text(70, 64, "Tandem architecture", 30, TF["txt"], 800, sp=1))
    o.append(_tf_text(70, 92, "Three products, three repositories, four "
                      "optional HTTP links.", 14, TF["t2"]))

    # The gateway spans everything below it because that is what it does: one
    # identity's erasure, export, consent and metering across all three.
    o.append(_tf_panel(
        70, 120, 1040, 84, "suite gateway — qrme/suite/gateway.py",
        ["POST /suite/erase · POST /suite/export · PUT /suite/consent · "
         "POST /suite/usage",
         "one linked identity · a per-product receipt, so a partial failure "
         "is visible rather than swallowed"],
        TF["t2"]))

    o.append(_tf_panel(
        70, 274, 320, 140, "jim-mini — Guardian",
        ["monitor → predict → guide → escalate",
         "life layer · check-in · journal",
         "care beacons · workplace relay"], TF["jim"]))
    o.append(_tf_panel(
        560, 274, 320, 140, "qrme — synthetic profiles",
        ["relationship-aware · remembered",
         "moderation · the burned-in AI mark",
         "live desks · beacons · marketplace"], TF["qrme"]))
    o.append(_tf_panel(
        70, 512, 1040, 104, "pdi — Private Data Infrastructure",
        ["AES-256-GCM vault · per-tenant isolation · tamper-evident audit "
         "chain · BYOK",
         "custody beacons · the agent at the gate — the model is the voice, "
         "not the decider"], TF["pdi"]))

    # Gateway down into each product. The run to PDI keeps to the far right so
    # it never crosses a panel or a label.
    o.append(_tf_arrow(170, 204, 170, 274, "gw"))
    o.append(_tf_arrow(660, 204, 660, 274, "gw"))
    o.append(_tf_arrow(1060, 204, 1060, 512, "gw"))

    # jim → qrme: guidance.
    o.append(_tf_arrow(390, 330, 560, 330, "jim"))
    o.append(_tf_text(475, 318, "specialist guidance", 12.5, TF["jim"], 600,
                      "middle"))

    # Both apps seal into the vault, and the label has to name what actually
    # goes down these arrows. "medical payloads" was true and incomplete: a
    # user's bank and spending events ride the same wire under the same
    # consent gate, and a diagram naming only the medical half invites the
    # reader to assume the financial half is held somewhere else. It is not.
    # Messages and location sit on the same line for the same reason: the
    # bold line is the surprising ones, and burying two of them a row down
    # would have re-made the mistake in a smaller font.
    o.append(_tf_arrow(150, 414, 150, 512, "jim"))
    o.append(_tf_text(164, 444,
                      "medical \u00b7 financial \u00b7 messages \u00b7 location",
                      12.5, TF["jim"], 600))
    o.append(_tf_text(164, 462, "calendar \u00b7 wearable \u00b7 health", 12,
                      TF["t2"]))
    o.append(_tf_text(164, 480, "sealed under jim/{user}/\u2026", 12, TF["t3"]))
    o.append(_tf_arrow(610, 414, 610, 512, "qrme"))
    o.append(_tf_text(624, 444, "source material", 12.5, TF["qrme"], 600))
    o.append(_tf_text(624, 462, "rated events \u00b7 adaptation", 12, TF["t2"]))
    o.append(_tf_text(624, 480, "sealed under qrme/{profile}/\u2026", 12,
                      TF["t3"]))

    # \u2026and the one that runs the other way.
    o.append(_tf_arrow(850, 512, 850, 414, "out"))
    o.append(_tf_text(864, 444, "words for the gate", 12.5, TF["out"], 600))
    o.append(_tf_text(864, 462, "never a decision", 12, TF["t3"]))

    o.append(_tf_text(70, 656, "Every link is optional and runs over public "
                      "HTTP — no project imports another's code. Dashed "
                      "because each product runs alone with none of them "
                      "configured.", 12.5, TF["t3"]))
    o.append(_tf_text(70, 676, "Amber is the only link that runs out of PDI: "
                      "the gate agent asks a QRME profile for words after the "
                      "decision is already made, and nothing generated can "
                      "change it.", 12.5, TF["t3"]))
    o.append("</svg>")
    return "".join(o)


DIAGRAMS = {"tandem-flow.svg": tandem_flow}
DIAG_OUT = os.path.join(ROOT, "docs", "diagrams")

ASSETS = {
    "cover.svg": cover,
    "guardian-tandem.svg": guardian_tandem,
    "life-layer.svg": life_layer,
    "embodiments.svg": embodiments,
}


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    for name, fn in ASSETS.items():
        with open(os.path.join(OUT, name), "w") as f:
            f.write(fn())
        print(f"wrote assets/{name}")
    os.makedirs(DIAG_OUT, exist_ok=True)
    for name, fn in DIAGRAMS.items():
        with open(os.path.join(DIAG_OUT, name), "w") as f:
            f.write(fn())
        print(f"wrote docs/diagrams/{name}")


if __name__ == "__main__":
    main()
